// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Smuxi.Frontend.Gnome {
    
    
    public partial class EngineAssistantNameWidget {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Label f_EngineNameLabel;
        
        private Gtk.Entry f_EngineNameEntry;
        
        private Gtk.Label label2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Smuxi.Frontend.Gnome.EngineAssistantNameWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "Smuxi.Frontend.Gnome.EngineAssistantNameWidget";
            // Container child Smuxi.Frontend.Gnome.EngineAssistantNameWidget.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            this.vbox2.BorderWidth = ((uint)(5));
            // Container child vbox2.Gtk.Box+BoxChild
            this.f_EngineNameLabel = new Gtk.Label();
            this.f_EngineNameLabel.Name = "f_EngineNameLabel";
            this.f_EngineNameLabel.Xalign = 0F;
            this.f_EngineNameLabel.LabelProp = Mono.Unix.Catalog.GetString("_Engine Name:");
            this.f_EngineNameLabel.UseUnderline = true;
            this.vbox2.Add(this.f_EngineNameLabel);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox2[this.f_EngineNameLabel]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.f_EngineNameEntry = new Gtk.Entry();
            this.f_EngineNameEntry.CanFocus = true;
            this.f_EngineNameEntry.Name = "f_EngineNameEntry";
            this.f_EngineNameEntry.IsEditable = true;
            this.f_EngineNameEntry.InvisibleChar = '●';
            this.vbox2.Add(this.f_EngineNameEntry);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.f_EngineNameEntry]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 0.1F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("<span size=\"small\">Profile name of the new engine</span>");
            this.label2.UseMarkup = true;
            this.vbox2.Add(this.label2);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.label2]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.f_EngineNameLabel.MnemonicWidget = this.f_EngineNameEntry;
            this.Hide();
        }
    }
}
