// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Smuxi.Frontend.Gnome {
    
    
    public partial class ChatTypeWidget {
        
        private Gtk.ComboBox f_ComboBox;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Smuxi.Frontend.Gnome.ChatTypeWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "Smuxi.Frontend.Gnome.ChatTypeWidget";
            // Container child Smuxi.Frontend.Gnome.ChatTypeWidget.Gtk.Container+ContainerChild
            this.f_ComboBox = Gtk.ComboBox.NewText();
            this.f_ComboBox.Name = "f_ComboBox";
            this.Add(this.f_ComboBox);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
