
// This file has been generated by the GUI designer. Do not modify.
namespace Smuxi.Frontend.Gnome
{
	public partial class FilterListWidget
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.TreeView f_TreeView;

		private global::Gtk.VButtonBox vbuttonbox1;

		private global::Gtk.Button f_AddButton;

		private global::Gtk.Button f_RemoveButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Smuxi.Frontend.Gnome.FilterListWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Smuxi.Frontend.Gnome.FilterListWidget";
			// Container child Smuxi.Frontend.Gnome.FilterListWidget.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 5;
			// Container child hbox1.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.f_TreeView = new global::Gtk.TreeView ();
			this.f_TreeView.CanFocus = true;
			this.f_TreeView.Name = "f_TreeView";
			this.scrolledwindow1.Add (this.f_TreeView);
			this.hbox1.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.scrolledwindow1]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbuttonbox1 = new global::Gtk.VButtonBox ();
			this.vbuttonbox1.Name = "vbuttonbox1";
			this.vbuttonbox1.BorderWidth = ((uint)(5));
			this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.f_AddButton = new global::Gtk.Button ();
			this.f_AddButton.CanFocus = true;
			this.f_AddButton.Name = "f_AddButton";
			this.f_AddButton.UseStock = true;
			this.f_AddButton.UseUnderline = true;
			this.f_AddButton.Label = "gtk-add";
			this.vbuttonbox1.Add (this.f_AddButton);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.f_AddButton]));
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.f_RemoveButton = new global::Gtk.Button ();
			this.f_RemoveButton.CanFocus = true;
			this.f_RemoveButton.Name = "f_RemoveButton";
			this.f_RemoveButton.UseStock = true;
			this.f_RemoveButton.UseUnderline = true;
			this.f_RemoveButton.Label = "gtk-remove";
			this.vbuttonbox1.Add (this.f_RemoveButton);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.f_RemoveButton]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.hbox1.Add (this.vbuttonbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbuttonbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.f_AddButton.Clicked += new global::System.EventHandler (this.OnAddButtonClicked);
			this.f_RemoveButton.Clicked += new global::System.EventHandler (this.OnRemoveButtonClicked);
		}
	}
}
