
// This file has been generated by the GUI designer. Do not modify.
namespace Smuxi.Frontend.Gnome
{
	public partial class SteticPreferencesDialog
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.ScrolledWindow MenuScrolledWindow;
		private global::Gtk.TreeView MenuTreeView;
		private global::Gtk.Notebook Notebook;
		private global::Gtk.VBox vbox1;
		private global::Gtk.Table table1;
		private global::Gtk.Entry ConnectionNicknamesEntry;
		private global::Gtk.Entry ConnectionRealnameEntry;
		private global::Gtk.Entry ConnectionUsernameEntry;
		private global::Gtk.ComboBox EncodingComboBox;
		private global::Gtk.HBox hbox13;
		private global::Gtk.Label label6;
		private global::Gtk.Fixed fixed31;
		private global::Gtk.HBox hbox14;
		private global::Gtk.Label label7;
		private global::Gtk.Fixed fixed32;
		private global::Gtk.HBox hbox15;
		private global::Gtk.Label label8;
		private global::Gtk.Fixed fixed33;
		private global::Gtk.Label label58;
		private global::Gtk.VBox vbox2;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label37;
		private global::Gtk.Fixed fixed18;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.TextView OnConnectCommandsTextView;
		private global::Gtk.VBox vbox4;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label label43;
		private global::Gtk.Fixed fixed19;
		private global::Gtk.ScrolledWindow scrolledwindow2;
		private global::Gtk.TextView OnStartupCommandsTextView;
		private global::Gtk.Label label44;
		private global::Gtk.Notebook InterfaceNotebook;
		private global::Gtk.VBox vbox10;
		private global::Gtk.Table table5;
		private global::Gtk.SpinButton BufferLinesSpinButton;
		private global::Gtk.SpinButton EngineBufferLinesSpinButton;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Label label33;
		private global::Gtk.Fixed fixed25;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Label label39;
		private global::Gtk.Fixed fixed26;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Label label40;
		private global::Gtk.Fixed fixed27;
		private global::Gtk.Entry TimestampFormatEntry;
		private global::Gtk.CheckButton StripColorsCheckButton;
		private global::Gtk.Alignment alignment16;
		private global::Gtk.HBox hbox17;
		private global::Gtk.Image image5;
		private global::Gtk.Label label47;
		private global::Gtk.CheckButton StripFormattingsCheckButton;
		private global::Gtk.Alignment alignment15;
		private global::Gtk.HBox hbox16;
		private global::Gtk.Image image6;
		private global::Gtk.Label label46;
		private global::Gtk.CheckButton checkbutton1;
		private global::Gtk.Alignment alignment26;
		private global::Gtk.HBox hbox28;
		private global::Gtk.Image image7;
		private global::Gtk.Label label60;
		private global::Gtk.Label label1;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment alignment4;
		private global::Gtk.VBox vbox6;
		private global::Gtk.RadioButton TabPositionRadioButtonTop;
		private global::Gtk.HBox hbox10;
		private global::Gtk.Image image12;
		private global::Gtk.Label label5;
		private global::Gtk.RadioButton TabPositionRadioButtonBottom;
		private global::Gtk.HBox hbox24;
		private global::Gtk.Image image9;
		private global::Gtk.Label label54;
		private global::Gtk.RadioButton TabPositionRadioButtonLeft;
		private global::Gtk.Alignment alignment24;
		private global::Gtk.HBox hbox25;
		private global::Gtk.Image image10;
		private global::Gtk.Label label55;
		private global::Gtk.RadioButton TabPositionRadioButtonRight;
		private global::Gtk.Alignment alignment25;
		private global::Gtk.HBox hbox26;
		private global::Gtk.Image image11;
		private global::Gtk.Label label56;
		private global::Gtk.RadioButton TabPositionRadioButtonNone;
		private global::Gtk.Label label9;
		private global::Gtk.Frame frame4;
		private global::Gtk.Alignment alignment8;
		private global::Gtk.Table table3;
		private global::Gtk.ColorButton ActivityColorButton;
		private global::Gtk.ColorButton HighlightColorButton;
		private global::Gtk.Label label16;
		private global::Gtk.Label label17;
		private global::Gtk.Label label18;
		private global::Gtk.Label label59;
		private global::Gtk.ColorButton ModeColorButton;
		private global::Gtk.ColorButton NoActivityColorButton;
		private global::Gtk.Label label15;
		private global::Gtk.Label label2;
		private global::Gtk.Frame frame3;
		private global::Gtk.Alignment alignment7;
		private global::Gtk.VBox vbox7;
		private global::Gtk.Table table4;
		private global::Gtk.Entry CommandCharacterEntry;
		private global::Gtk.SpinButton CommandHistorySizeSpinButton;
		private global::Gtk.Entry CompletionCharacterEntry;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label label13;
		private global::Gtk.Fixed fixed22;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label label14;
		private global::Gtk.Fixed fixed23;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label label42;
		private global::Gtk.Fixed fixed24;
		private global::Gtk.CheckButton BashStyleCompletionCheckButton;
		private global::Gtk.Label label12;
		private global::Gtk.Label label3;
		private global::Gtk.VBox vbox8;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.VBox vbox9;
		private global::Gtk.CheckButton NickColorsCheckButton;
		private global::Gtk.Frame frame10;
		private global::Gtk.Alignment alignment14;
		private global::Gtk.VBox vbox11;
		private global::Gtk.RadioButton TopicPositionRadioButtonTop;
		private global::Gtk.Alignment alignment21;
		private global::Gtk.HBox hbox22;
		private global::Gtk.Image image1;
		private global::Gtk.Label label52;
		private global::Gtk.RadioButton TopicPositionRadioButtonBottom;
		private global::Gtk.Alignment alignment20;
		private global::Gtk.HBox hbox21;
		private global::Gtk.Image image2;
		private global::Gtk.Label label51;
		private global::Gtk.RadioButton TopicPositionRadioButtonNone;
		private global::Gtk.Label label41;
		private global::Gtk.Frame frame9;
		private global::Gtk.Alignment alignment13;
		private global::Gtk.VBox vbox12;
		private global::Gtk.RadioButton UserListPositionRadioButtonLeft;
		private global::Gtk.Alignment alignment17;
		private global::Gtk.HBox hbox18;
		private global::Gtk.Image image3;
		private global::Gtk.Label label48;
		private global::Gtk.RadioButton UserListPositionRadioButtonRight;
		private global::Gtk.Alignment alignment18;
		private global::Gtk.HBox hbox19;
		private global::Gtk.Image image4;
		private global::Gtk.Label label49;
		private global::Gtk.RadioButton UserListPositionRadioButtonNone;
		private global::Gtk.Label label38;
		private global::Gtk.Label label10;
		private global::Gtk.Frame frame11;
		private global::Gtk.Alignment alignment27;
		private global::Gtk.VBox vbox13;
		private global::Gtk.VBox vbox14;
		private global::Gtk.Label label62;
		private global::Gtk.ScrolledWindow scrolledwindow4;
		private global::Gtk.TextView HighlightWordsTextView;
		private global::Gtk.CheckButton BeepOnHighlightCheckButton;
		private global::Gtk.Label label61;
		private global::Gtk.Label label4;
		private global::Gtk.Label label45;
		private global::Gtk.HBox hbox27;
		private global::Gtk.ScrolledWindow scrolledwindow3;
		private global::Gtk.TreeView ServersTreeView;
		private global::Gtk.VButtonBox vbuttonbox1;
		private global::Gtk.Button ServersAddButton;
		private global::Gtk.Button ServersEditButton;
		private global::Gtk.Button ServersRemoveButton;
		private global::Gtk.Label label57;
		private global::Gtk.VBox vbox15;
		private global::Gtk.Frame frame12;
		private global::Gtk.Alignment alignment28;
		private global::Gtk.VBox vbox16;
		private global::Gtk.ScrolledWindow scrolledwindow5;
		private global::Gtk.TreeView ChannelFiltersTreeView;
		private global::Gtk.HButtonBox hbuttonbox1;
		private global::Gtk.Button ChannelFiltersAddButton;
		private global::Gtk.Button ChannelFiltersRemoveButton;
		private global::Gtk.Label label64;
		private global::Gtk.Frame frame13;
		private global::Gtk.Alignment alignment29;
		private global::Gtk.Label label65;
		private global::Gtk.Label label63;
		private global::Gtk.Button CancelButton;
		private global::Gtk.Button ApplyButton;
		private global::Gtk.Button OKButton;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Smuxi.Frontend.Gnome.SteticPreferencesDialog
			this.Name = "Smuxi.Frontend.Gnome.SteticPreferencesDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Smuxi - Preferences");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			// Internal child Smuxi.Frontend.Gnome.SteticPreferencesDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog-vbox1";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog-vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.BorderWidth = ((uint)(10));
			// Container child hbox1.Gtk.Box+BoxChild
			this.MenuScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.MenuScrolledWindow.WidthRequest = 128;
			this.MenuScrolledWindow.Name = "MenuScrolledWindow";
			this.MenuScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child MenuScrolledWindow.Gtk.Container+ContainerChild
			this.MenuTreeView = new global::Gtk.TreeView ();
			this.MenuTreeView.Name = "MenuTreeView";
			this.MenuTreeView.EnableSearch = false;
			this.MenuTreeView.HeadersVisible = false;
			this.MenuScrolledWindow.Add (this.MenuTreeView);
			this.hbox1.Add (this.MenuScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.MenuScrolledWindow]));
			w3.Position = 0;
			w3.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.Notebook = new global::Gtk.Notebook ();
			this.Notebook.Name = "Notebook";
			this.Notebook.CurrentPage = 0;
			this.Notebook.ShowBorder = false;
			// Container child Notebook.Gtk.Notebook+NotebookChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 5;
			this.vbox1.BorderWidth = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(5));
			this.table1.ColumnSpacing = ((uint)(5));
			// Container child table1.Gtk.Table+TableChild
			this.ConnectionNicknamesEntry = new global::Gtk.Entry ();
			this.ConnectionNicknamesEntry.Name = "ConnectionNicknamesEntry";
			this.ConnectionNicknamesEntry.IsEditable = true;
			this.ConnectionNicknamesEntry.InvisibleChar = '●';
			this.table1.Add (this.ConnectionNicknamesEntry);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.ConnectionNicknamesEntry]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table1.Gtk.Table+TableChild
			this.ConnectionRealnameEntry = new global::Gtk.Entry ();
			this.ConnectionRealnameEntry.Name = "ConnectionRealnameEntry";
			this.ConnectionRealnameEntry.IsEditable = true;
			this.ConnectionRealnameEntry.InvisibleChar = '●';
			this.table1.Add (this.ConnectionRealnameEntry);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.ConnectionRealnameEntry]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table1.Gtk.Table+TableChild
			this.ConnectionUsernameEntry = new global::Gtk.Entry ();
			this.ConnectionUsernameEntry.Name = "ConnectionUsernameEntry";
			this.ConnectionUsernameEntry.IsEditable = true;
			this.ConnectionUsernameEntry.InvisibleChar = '●';
			this.table1.Add (this.ConnectionUsernameEntry);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.ConnectionUsernameEntry]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table1.Gtk.Table+TableChild
			this.EncodingComboBox = new global::Gtk.ComboBox ();
			this.EncodingComboBox.Name = "EncodingComboBox";
			this.table1.Add (this.EncodingComboBox);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.EncodingComboBox]));
			w7.TopAttach = ((uint)(3));
			w7.BottomAttach = ((uint)(4));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			// Container child hbox13.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Nicknames:");
			this.hbox13.Add (this.label6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label6]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.fixed31 = new global::Gtk.Fixed ();
			this.fixed31.Name = "fixed31";
			this.fixed31.HasWindow = false;
			this.hbox13.Add (this.fixed31);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.fixed31]));
			w9.Position = 1;
			this.table1.Add (this.hbox13);
			// Container child table1.Gtk.Table+TableChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			// Container child hbox14.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Username:");
			this.hbox14.Add (this.label7);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label7]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.fixed32 = new global::Gtk.Fixed ();
			this.fixed32.Name = "fixed32";
			this.fixed32.HasWindow = false;
			this.hbox14.Add (this.fixed32);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.fixed32]));
			w12.Position = 1;
			this.table1.Add (this.hbox14);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox14]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			// Container child hbox15.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Realname:");
			this.hbox15.Add (this.label8);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label8]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.fixed33 = new global::Gtk.Fixed ();
			this.fixed33.Name = "fixed33";
			this.fixed33.HasWindow = false;
			this.hbox15.Add (this.fixed33);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.fixed33]));
			w15.Position = 1;
			this.table1.Add (this.hbox15);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox15]));
			w16.TopAttach = ((uint)(2));
			w16.BottomAttach = ((uint)(3));
			// Container child table1.Gtk.Table+TableChild
			this.label58 = new global::Gtk.Label ();
			this.label58.Name = "label58";
			this.label58.Xalign = 0F;
			this.label58.LabelProp = global::Mono.Unix.Catalog.GetString ("Encoding:");
			this.table1.Add (this.label58);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.label58]));
			w17.TopAttach = ((uint)(3));
			w17.BottomAttach = ((uint)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(0));
			this.vbox1.Add (this.table1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
			w18.Position = 0;
			w18.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			// Container child hbox2.Gtk.Box+BoxChild
			this.label37 = new global::Gtk.Label ();
			this.label37.Name = "label37";
			this.label37.LabelProp = global::Mono.Unix.Catalog.GetString ("On Connect Commands:");
			this.hbox2.Add (this.label37);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label37]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed18 = new global::Gtk.Fixed ();
			this.fixed18.Name = "fixed18";
			this.fixed18.HasWindow = false;
			this.hbox2.Add (this.fixed18);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed18]));
			w20.Position = 1;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.WidthRequest = 350;
			this.scrolledwindow1.HeightRequest = 100;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.OnConnectCommandsTextView = new global::Gtk.TextView ();
			this.OnConnectCommandsTextView.WidthRequest = 152;
			this.OnConnectCommandsTextView.HeightRequest = 168;
			this.OnConnectCommandsTextView.Name = "OnConnectCommandsTextView";
			this.OnConnectCommandsTextView.WrapMode = ((global::Gtk.WrapMode)(2));
			this.scrolledwindow1.Add (this.OnConnectCommandsTextView);
			this.vbox3.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.scrolledwindow1]));
			w23.Position = 1;
			this.vbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
			w24.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			// Container child hbox3.Gtk.Box+BoxChild
			this.label43 = new global::Gtk.Label ();
			this.label43.Name = "label43";
			this.label43.LabelProp = global::Mono.Unix.Catalog.GetString ("On Startup Commands:");
			this.hbox3.Add (this.label43);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label43]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.fixed19 = new global::Gtk.Fixed ();
			this.fixed19.Name = "fixed19";
			this.fixed19.HasWindow = false;
			this.hbox3.Add (this.fixed19);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.fixed19]));
			w26.Position = 1;
			this.vbox4.Add (this.hbox3);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.WidthRequest = 350;
			this.scrolledwindow2.HeightRequest = 100;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			this.OnStartupCommandsTextView = new global::Gtk.TextView ();
			this.OnStartupCommandsTextView.WidthRequest = 152;
			this.OnStartupCommandsTextView.HeightRequest = 168;
			this.OnStartupCommandsTextView.Name = "OnStartupCommandsTextView";
			this.OnStartupCommandsTextView.WrapMode = ((global::Gtk.WrapMode)(2));
			this.scrolledwindow2.Add (this.OnStartupCommandsTextView);
			this.vbox4.Add (this.scrolledwindow2);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.scrolledwindow2]));
			w29.Position = 1;
			this.vbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox4]));
			w30.Position = 1;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w31.Position = 1;
			this.Notebook.Add (this.vbox1);
			// Notebook tab
			this.label44 = new global::Gtk.Label ();
			this.label44.Name = "label44";
			this.label44.LabelProp = global::Mono.Unix.Catalog.GetString ("C_onnection");
			this.label44.UseUnderline = true;
			this.Notebook.SetTabLabel (this.vbox1, this.label44);
			this.label44.ShowAll ();
			// Container child Notebook.Gtk.Notebook+NotebookChild
			this.InterfaceNotebook = new global::Gtk.Notebook ();
			this.InterfaceNotebook.Name = "InterfaceNotebook";
			this.InterfaceNotebook.CurrentPage = 0;
			// Container child InterfaceNotebook.Gtk.Notebook+NotebookChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			// Container child vbox10.Gtk.Box+BoxChild
			this.table5 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(5));
			this.table5.ColumnSpacing = ((uint)(5));
			this.table5.BorderWidth = ((uint)(5));
			// Container child table5.Gtk.Table+TableChild
			this.BufferLinesSpinButton = new global::Gtk.SpinButton (1, 9999, 1);
			this.BufferLinesSpinButton.WidthRequest = 60;
			this.BufferLinesSpinButton.Name = "BufferLinesSpinButton";
			this.BufferLinesSpinButton.Adjustment.PageIncrement = 10;
			this.BufferLinesSpinButton.Adjustment.PageSize = 10;
			this.BufferLinesSpinButton.ClimbRate = 1;
			this.BufferLinesSpinButton.Numeric = true;
			this.BufferLinesSpinButton.Value = 200;
			this.table5.Add (this.BufferLinesSpinButton);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table5 [this.BufferLinesSpinButton]));
			w33.TopAttach = ((uint)(1));
			w33.BottomAttach = ((uint)(2));
			w33.LeftAttach = ((uint)(1));
			w33.RightAttach = ((uint)(2));
			w33.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table5.Gtk.Table+TableChild
			this.EngineBufferLinesSpinButton = new global::Gtk.SpinButton (0, 9999, 1);
			this.EngineBufferLinesSpinButton.WidthRequest = 60;
			this.EngineBufferLinesSpinButton.Name = "EngineBufferLinesSpinButton";
			this.EngineBufferLinesSpinButton.Adjustment.PageIncrement = 10;
			this.EngineBufferLinesSpinButton.Adjustment.PageSize = 10;
			this.EngineBufferLinesSpinButton.ClimbRate = 1;
			this.EngineBufferLinesSpinButton.Numeric = true;
			this.EngineBufferLinesSpinButton.Value = 200;
			this.table5.Add (this.EngineBufferLinesSpinButton);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table5 [this.EngineBufferLinesSpinButton]));
			w34.TopAttach = ((uint)(2));
			w34.BottomAttach = ((uint)(3));
			w34.LeftAttach = ((uint)(1));
			w34.RightAttach = ((uint)(2));
			w34.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table5.Gtk.Table+TableChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			// Container child hbox7.Gtk.Box+BoxChild
			this.label33 = new global::Gtk.Label ();
			this.label33.Name = "label33";
			this.label33.LabelProp = global::Mono.Unix.Catalog.GetString ("Timestamp Format:");
			this.hbox7.Add (this.label33);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label33]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.fixed25 = new global::Gtk.Fixed ();
			this.fixed25.Name = "fixed25";
			this.fixed25.HasWindow = false;
			this.hbox7.Add (this.fixed25);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.fixed25]));
			w36.Position = 1;
			this.table5.Add (this.hbox7);
			// Container child table5.Gtk.Table+TableChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			// Container child hbox8.Gtk.Box+BoxChild
			this.label39 = new global::Gtk.Label ();
			this.label39.Name = "label39";
			this.label39.LabelProp = global::Mono.Unix.Catalog.GetString ("Buffer Lines:");
			this.hbox8.Add (this.label39);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label39]));
			w38.Position = 0;
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.fixed26 = new global::Gtk.Fixed ();
			this.fixed26.Name = "fixed26";
			this.fixed26.HasWindow = false;
			this.hbox8.Add (this.fixed26);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.fixed26]));
			w39.Position = 1;
			this.table5.Add (this.hbox8);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table5 [this.hbox8]));
			w40.TopAttach = ((uint)(1));
			w40.BottomAttach = ((uint)(2));
			// Container child table5.Gtk.Table+TableChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			// Container child hbox9.Gtk.Box+BoxChild
			this.label40 = new global::Gtk.Label ();
			this.label40.Name = "label40";
			this.label40.LabelProp = global::Mono.Unix.Catalog.GetString ("Engine Buffer Lines:");
			this.hbox9.Add (this.label40);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label40]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.fixed27 = new global::Gtk.Fixed ();
			this.fixed27.Name = "fixed27";
			this.fixed27.HasWindow = false;
			this.hbox9.Add (this.fixed27);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.fixed27]));
			w42.Position = 1;
			this.table5.Add (this.hbox9);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table5 [this.hbox9]));
			w43.TopAttach = ((uint)(2));
			w43.BottomAttach = ((uint)(3));
			// Container child table5.Gtk.Table+TableChild
			this.TimestampFormatEntry = new global::Gtk.Entry ();
			this.TimestampFormatEntry.WidthRequest = 60;
			this.TimestampFormatEntry.Name = "TimestampFormatEntry";
			this.TimestampFormatEntry.Text = "HH:mm";
			this.TimestampFormatEntry.IsEditable = true;
			this.TimestampFormatEntry.InvisibleChar = '●';
			this.table5.Add (this.TimestampFormatEntry);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table5 [this.TimestampFormatEntry]));
			w44.LeftAttach = ((uint)(1));
			w44.RightAttach = ((uint)(2));
			w44.YOptions = ((global::Gtk.AttachOptions)(0));
			this.vbox10.Add (this.table5);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.table5]));
			w45.Position = 0;
			w45.Expand = false;
			w45.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.StripColorsCheckButton = new global::Gtk.CheckButton ();
			this.StripColorsCheckButton.Name = "StripColorsCheckButton";
			this.StripColorsCheckButton.DrawIndicator = true;
			this.StripColorsCheckButton.UseUnderline = true;
			this.StripColorsCheckButton.Remove (this.StripColorsCheckButton.Child);
			// Container child StripColorsCheckButton.Gtk.Container+ContainerChild
			this.alignment16 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			this.alignment16.Name = "alignment16";
			// Container child alignment16.Gtk.Container+ContainerChild
			this.hbox17 = new global::Gtk.HBox ();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 2;
			// Container child hbox17.Gtk.Box+BoxChild
			this.image5 = new global::Gtk.Image ();
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cut", global::Gtk.IconSize.Menu);
			this.hbox17.Add (this.image5);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.image5]));
			w46.Position = 0;
			w46.Expand = false;
			w46.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.label47 = new global::Gtk.Label ();
			this.label47.Name = "label47";
			this.label47.LabelProp = global::Mono.Unix.Catalog.GetString ("Strip Colors");
			this.label47.UseUnderline = true;
			this.hbox17.Add (this.label47);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.label47]));
			w47.Position = 1;
			w47.Expand = false;
			w47.Fill = false;
			this.alignment16.Add (this.hbox17);
			this.StripColorsCheckButton.Add (this.alignment16);
			this.vbox10.Add (this.StripColorsCheckButton);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.StripColorsCheckButton]));
			w50.Position = 1;
			w50.Expand = false;
			w50.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.StripFormattingsCheckButton = new global::Gtk.CheckButton ();
			this.StripFormattingsCheckButton.Name = "StripFormattingsCheckButton";
			this.StripFormattingsCheckButton.DrawIndicator = true;
			this.StripFormattingsCheckButton.UseUnderline = true;
			this.StripFormattingsCheckButton.Remove (this.StripFormattingsCheckButton.Child);
			// Container child StripFormattingsCheckButton.Gtk.Container+ContainerChild
			this.alignment15 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			this.alignment15.Name = "alignment15";
			// Container child alignment15.Gtk.Container+ContainerChild
			this.hbox16 = new global::Gtk.HBox ();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 2;
			// Container child hbox16.Gtk.Box+BoxChild
			this.image6 = new global::Gtk.Image ();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cut", global::Gtk.IconSize.Menu);
			this.hbox16.Add (this.image6);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.image6]));
			w51.Position = 0;
			w51.Expand = false;
			w51.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.label46 = new global::Gtk.Label ();
			this.label46.Name = "label46";
			this.label46.LabelProp = global::Mono.Unix.Catalog.GetString ("Strip Formattings");
			this.label46.UseUnderline = true;
			this.hbox16.Add (this.label46);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.label46]));
			w52.Position = 1;
			w52.Expand = false;
			w52.Fill = false;
			this.alignment15.Add (this.hbox16);
			this.StripFormattingsCheckButton.Add (this.alignment15);
			this.vbox10.Add (this.StripFormattingsCheckButton);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.StripFormattingsCheckButton]));
			w55.Position = 2;
			w55.Expand = false;
			w55.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.checkbutton1 = new global::Gtk.CheckButton ();
			this.checkbutton1.Sensitive = false;
			this.checkbutton1.Name = "checkbutton1";
			this.checkbutton1.DrawIndicator = true;
			this.checkbutton1.UseUnderline = true;
			this.checkbutton1.Remove (this.checkbutton1.Child);
			// Container child checkbutton1.Gtk.Container+ContainerChild
			this.alignment26 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			this.alignment26.Name = "alignment26";
			// Container child alignment26.Gtk.Container+ContainerChild
			this.hbox28 = new global::Gtk.HBox ();
			this.hbox28.Name = "hbox28";
			this.hbox28.Spacing = 2;
			// Container child hbox28.Gtk.Box+BoxChild
			this.image7 = new global::Gtk.Image ();
			this.image7.Name = "image7";
			this.image7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cut", global::Gtk.IconSize.Menu);
			this.hbox28.Add (this.image7);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox28 [this.image7]));
			w56.Position = 0;
			w56.Expand = false;
			w56.Fill = false;
			// Container child hbox28.Gtk.Box+BoxChild
			this.label60 = new global::Gtk.Label ();
			this.label60.Name = "label60";
			this.label60.LabelProp = global::Mono.Unix.Catalog.GetString ("Strip UTF-8");
			this.label60.UseUnderline = true;
			this.hbox28.Add (this.label60);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox28 [this.label60]));
			w57.Position = 1;
			w57.Expand = false;
			w57.Fill = false;
			this.alignment26.Add (this.hbox28);
			this.checkbutton1.Add (this.alignment26);
			this.vbox10.Add (this.checkbutton1);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.checkbutton1]));
			w60.Position = 3;
			w60.Expand = false;
			w60.Fill = false;
			this.InterfaceNotebook.Add (this.vbox10);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("General");
			this.InterfaceNotebook.SetTabLabel (this.vbox10, this.label1);
			this.label1.ShowAll ();
			// Container child InterfaceNotebook.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 5;
			// Container child vbox5.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			// Container child frame1.Gtk.Container+ContainerChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.alignment4.LeftPadding = ((uint)(12));
			// Container child alignment4.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			// Container child vbox6.Gtk.Box+BoxChild
			this.TabPositionRadioButtonTop = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Top"));
			this.TabPositionRadioButtonTop.CanFocus = true;
			this.TabPositionRadioButtonTop.Name = "TabPositionRadioButtonTop";
			this.TabPositionRadioButtonTop.Active = true;
			this.TabPositionRadioButtonTop.DrawIndicator = true;
			this.TabPositionRadioButtonTop.UseUnderline = true;
			this.TabPositionRadioButtonTop.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.TabPositionRadioButtonTop.Remove (this.TabPositionRadioButtonTop.Child);
			// Container child TabPositionRadioButtonTop.Gtk.Container+ContainerChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.image12 = new global::Gtk.Image ();
			this.image12.Name = "image12";
			this.image12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-top", global::Gtk.IconSize.Menu);
			this.hbox10.Add (this.image12);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.image12]));
			w62.Position = 0;
			w62.Expand = false;
			w62.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Top");
			this.hbox10.Add (this.label5);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label5]));
			w63.Position = 1;
			w63.Expand = false;
			w63.Fill = false;
			this.TabPositionRadioButtonTop.Add (this.hbox10);
			this.vbox6.Add (this.TabPositionRadioButtonTop);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.TabPositionRadioButtonTop]));
			w65.Position = 0;
			w65.Expand = false;
			w65.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.TabPositionRadioButtonBottom = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Bottom"));
			this.TabPositionRadioButtonBottom.Name = "TabPositionRadioButtonBottom";
			this.TabPositionRadioButtonBottom.DrawIndicator = true;
			this.TabPositionRadioButtonBottom.UseUnderline = true;
			this.TabPositionRadioButtonBottom.Group = this.TabPositionRadioButtonTop.Group;
			this.TabPositionRadioButtonBottom.Remove (this.TabPositionRadioButtonBottom.Child);
			// Container child TabPositionRadioButtonBottom.Gtk.Container+ContainerChild
			this.hbox24 = new global::Gtk.HBox ();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 2;
			// Container child hbox24.Gtk.Box+BoxChild
			this.image9 = new global::Gtk.Image ();
			this.image9.Name = "image9";
			this.image9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-bottom", global::Gtk.IconSize.Menu);
			this.hbox24.Add (this.image9);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.image9]));
			w66.Position = 0;
			w66.Expand = false;
			w66.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.label54 = new global::Gtk.Label ();
			this.label54.Name = "label54";
			this.label54.LabelProp = global::Mono.Unix.Catalog.GetString ("Bottom");
			this.label54.UseUnderline = true;
			this.hbox24.Add (this.label54);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.label54]));
			w67.Position = 1;
			w67.Expand = false;
			w67.Fill = false;
			this.TabPositionRadioButtonBottom.Add (this.hbox24);
			this.vbox6.Add (this.TabPositionRadioButtonBottom);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.TabPositionRadioButtonBottom]));
			w69.Position = 1;
			w69.Expand = false;
			w69.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.TabPositionRadioButtonLeft = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Left"));
			this.TabPositionRadioButtonLeft.Name = "TabPositionRadioButtonLeft";
			this.TabPositionRadioButtonLeft.DrawIndicator = true;
			this.TabPositionRadioButtonLeft.UseUnderline = true;
			this.TabPositionRadioButtonLeft.Group = this.TabPositionRadioButtonTop.Group;
			this.TabPositionRadioButtonLeft.Remove (this.TabPositionRadioButtonLeft.Child);
			// Container child TabPositionRadioButtonLeft.Gtk.Container+ContainerChild
			this.alignment24 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			this.alignment24.Name = "alignment24";
			// Container child alignment24.Gtk.Container+ContainerChild
			this.hbox25 = new global::Gtk.HBox ();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 2;
			// Container child hbox25.Gtk.Box+BoxChild
			this.image10 = new global::Gtk.Image ();
			this.image10.Name = "image10";
			this.image10.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-first", global::Gtk.IconSize.Menu);
			this.hbox25.Add (this.image10);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.image10]));
			w70.Position = 0;
			w70.Expand = false;
			w70.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.label55 = new global::Gtk.Label ();
			this.label55.Name = "label55";
			this.label55.LabelProp = global::Mono.Unix.Catalog.GetString ("Left");
			this.label55.UseUnderline = true;
			this.hbox25.Add (this.label55);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.label55]));
			w71.Position = 1;
			w71.Expand = false;
			w71.Fill = false;
			this.alignment24.Add (this.hbox25);
			this.TabPositionRadioButtonLeft.Add (this.alignment24);
			this.vbox6.Add (this.TabPositionRadioButtonLeft);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.TabPositionRadioButtonLeft]));
			w74.Position = 2;
			w74.Expand = false;
			w74.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.TabPositionRadioButtonRight = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Right"));
			this.TabPositionRadioButtonRight.Name = "TabPositionRadioButtonRight";
			this.TabPositionRadioButtonRight.DrawIndicator = true;
			this.TabPositionRadioButtonRight.UseUnderline = true;
			this.TabPositionRadioButtonRight.Group = this.TabPositionRadioButtonTop.Group;
			this.TabPositionRadioButtonRight.Remove (this.TabPositionRadioButtonRight.Child);
			// Container child TabPositionRadioButtonRight.Gtk.Container+ContainerChild
			this.alignment25 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			this.alignment25.Name = "alignment25";
			// Container child alignment25.Gtk.Container+ContainerChild
			this.hbox26 = new global::Gtk.HBox ();
			this.hbox26.Name = "hbox26";
			this.hbox26.Spacing = 2;
			// Container child hbox26.Gtk.Box+BoxChild
			this.image11 = new global::Gtk.Image ();
			this.image11.Name = "image11";
			this.image11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-last", global::Gtk.IconSize.Menu);
			this.hbox26.Add (this.image11);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.image11]));
			w75.Position = 0;
			w75.Expand = false;
			w75.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.label56 = new global::Gtk.Label ();
			this.label56.Name = "label56";
			this.label56.LabelProp = global::Mono.Unix.Catalog.GetString ("Right");
			this.label56.UseUnderline = true;
			this.hbox26.Add (this.label56);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.label56]));
			w76.Position = 1;
			w76.Expand = false;
			w76.Fill = false;
			this.alignment25.Add (this.hbox26);
			this.TabPositionRadioButtonRight.Add (this.alignment25);
			this.vbox6.Add (this.TabPositionRadioButtonRight);
			global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.TabPositionRadioButtonRight]));
			w79.Position = 3;
			w79.Expand = false;
			w79.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.TabPositionRadioButtonNone = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("None"));
			this.TabPositionRadioButtonNone.Name = "TabPositionRadioButtonNone";
			this.TabPositionRadioButtonNone.DrawIndicator = true;
			this.TabPositionRadioButtonNone.UseUnderline = true;
			this.TabPositionRadioButtonNone.Group = this.TabPositionRadioButtonTop.Group;
			this.vbox6.Add (this.TabPositionRadioButtonNone);
			global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.TabPositionRadioButtonNone]));
			w80.Position = 4;
			w80.Expand = false;
			w80.Fill = false;
			this.alignment4.Add (this.vbox6);
			this.frame1.Add (this.alignment4);
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("<b> Tabs Position </b>");
			this.label9.UseMarkup = true;
			this.frame1.LabelWidget = this.label9;
			this.vbox5.Add (this.frame1);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame1]));
			w83.Position = 0;
			w83.Expand = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			// Container child frame4.Gtk.Container+ContainerChild
			this.alignment8 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			this.alignment8.LeftPadding = ((uint)(12));
			// Container child alignment8.Gtk.Container+ContainerChild
			this.table3 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(5));
			this.table3.ColumnSpacing = ((uint)(5));
			// Container child table3.Gtk.Table+TableChild
			this.ActivityColorButton = new global::Gtk.ColorButton ();
			this.ActivityColorButton.Name = "ActivityColorButton";
			this.table3.Add (this.ActivityColorButton);
			global::Gtk.Table.TableChild w84 = ((global::Gtk.Table.TableChild)(this.table3 [this.ActivityColorButton]));
			w84.TopAttach = ((uint)(1));
			w84.BottomAttach = ((uint)(2));
			w84.LeftAttach = ((uint)(1));
			w84.RightAttach = ((uint)(2));
			w84.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table3.Gtk.Table+TableChild
			this.HighlightColorButton = new global::Gtk.ColorButton ();
			this.HighlightColorButton.Name = "HighlightColorButton";
			this.table3.Add (this.HighlightColorButton);
			global::Gtk.Table.TableChild w85 = ((global::Gtk.Table.TableChild)(this.table3 [this.HighlightColorButton]));
			w85.TopAttach = ((uint)(3));
			w85.BottomAttach = ((uint)(4));
			w85.LeftAttach = ((uint)(1));
			w85.RightAttach = ((uint)(2));
			w85.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table3.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.Xalign = 0F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("No Activity");
			this.table3.Add (this.label16);
			global::Gtk.Table.TableChild w86 = ((global::Gtk.Table.TableChild)(this.table3 [this.label16]));
			w86.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table3.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.Xalign = 0F;
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Activity");
			this.table3.Add (this.label17);
			global::Gtk.Table.TableChild w87 = ((global::Gtk.Table.TableChild)(this.table3 [this.label17]));
			w87.TopAttach = ((uint)(1));
			w87.BottomAttach = ((uint)(2));
			w87.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table3.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.Xalign = 0F;
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Join/Part/Mode");
			this.table3.Add (this.label18);
			global::Gtk.Table.TableChild w88 = ((global::Gtk.Table.TableChild)(this.table3 [this.label18]));
			w88.TopAttach = ((uint)(2));
			w88.BottomAttach = ((uint)(3));
			w88.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table3.Gtk.Table+TableChild
			this.label59 = new global::Gtk.Label ();
			this.label59.Name = "label59";
			this.label59.Xalign = 0F;
			this.label59.LabelProp = global::Mono.Unix.Catalog.GetString ("Highlight");
			this.table3.Add (this.label59);
			global::Gtk.Table.TableChild w89 = ((global::Gtk.Table.TableChild)(this.table3 [this.label59]));
			w89.TopAttach = ((uint)(3));
			w89.BottomAttach = ((uint)(4));
			w89.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table3.Gtk.Table+TableChild
			this.ModeColorButton = new global::Gtk.ColorButton ();
			this.ModeColorButton.Name = "ModeColorButton";
			this.table3.Add (this.ModeColorButton);
			global::Gtk.Table.TableChild w90 = ((global::Gtk.Table.TableChild)(this.table3 [this.ModeColorButton]));
			w90.TopAttach = ((uint)(2));
			w90.BottomAttach = ((uint)(3));
			w90.LeftAttach = ((uint)(1));
			w90.RightAttach = ((uint)(2));
			w90.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table3.Gtk.Table+TableChild
			this.NoActivityColorButton = new global::Gtk.ColorButton ();
			this.NoActivityColorButton.Name = "NoActivityColorButton";
			this.table3.Add (this.NoActivityColorButton);
			global::Gtk.Table.TableChild w91 = ((global::Gtk.Table.TableChild)(this.table3 [this.NoActivityColorButton]));
			w91.LeftAttach = ((uint)(1));
			w91.RightAttach = ((uint)(2));
			w91.YOptions = ((global::Gtk.AttachOptions)(0));
			this.alignment8.Add (this.table3);
			this.frame4.Add (this.alignment8);
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("<b> Tab Colors </b>");
			this.label15.UseMarkup = true;
			this.frame4.LabelWidget = this.label15;
			this.vbox5.Add (this.frame4);
			global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame4]));
			w94.Position = 1;
			w94.Expand = false;
			this.InterfaceNotebook.Add (this.vbox5);
			global::Gtk.Notebook.NotebookChild w95 = ((global::Gtk.Notebook.NotebookChild)(this.InterfaceNotebook [this.vbox5]));
			w95.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Tabs");
			this.InterfaceNotebook.SetTabLabel (this.vbox5, this.label2);
			this.label2.ShowAll ();
			// Container child InterfaceNotebook.Gtk.Notebook+NotebookChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			// Container child frame3.Gtk.Container+ContainerChild
			this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			this.alignment7.LeftPadding = ((uint)(12));
			// Container child alignment7.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 5;
			// Container child vbox7.Gtk.Box+BoxChild
			this.table4 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(5));
			this.table4.ColumnSpacing = ((uint)(5));
			this.table4.BorderWidth = ((uint)(5));
			// Container child table4.Gtk.Table+TableChild
			this.CommandCharacterEntry = new global::Gtk.Entry ();
			this.CommandCharacterEntry.WidthRequest = 30;
			this.CommandCharacterEntry.Name = "CommandCharacterEntry";
			this.CommandCharacterEntry.Text = "/";
			this.CommandCharacterEntry.IsEditable = true;
			this.CommandCharacterEntry.MaxLength = 1;
			this.CommandCharacterEntry.InvisibleChar = '●';
			this.table4.Add (this.CommandCharacterEntry);
			global::Gtk.Table.TableChild w96 = ((global::Gtk.Table.TableChild)(this.table4 [this.CommandCharacterEntry]));
			w96.TopAttach = ((uint)(1));
			w96.BottomAttach = ((uint)(2));
			w96.LeftAttach = ((uint)(1));
			w96.RightAttach = ((uint)(2));
			w96.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table4.Gtk.Table+TableChild
			this.CommandHistorySizeSpinButton = new global::Gtk.SpinButton (1, 9999, 1);
			this.CommandHistorySizeSpinButton.WidthRequest = 60;
			this.CommandHistorySizeSpinButton.Name = "CommandHistorySizeSpinButton";
			this.CommandHistorySizeSpinButton.Adjustment.PageIncrement = 10;
			this.CommandHistorySizeSpinButton.Adjustment.PageSize = 10;
			this.CommandHistorySizeSpinButton.ClimbRate = 1;
			this.CommandHistorySizeSpinButton.Numeric = true;
			this.CommandHistorySizeSpinButton.Value = 30;
			this.table4.Add (this.CommandHistorySizeSpinButton);
			global::Gtk.Table.TableChild w97 = ((global::Gtk.Table.TableChild)(this.table4 [this.CommandHistorySizeSpinButton]));
			w97.TopAttach = ((uint)(2));
			w97.BottomAttach = ((uint)(3));
			w97.LeftAttach = ((uint)(1));
			w97.RightAttach = ((uint)(2));
			w97.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table4.Gtk.Table+TableChild
			this.CompletionCharacterEntry = new global::Gtk.Entry ();
			this.CompletionCharacterEntry.WidthRequest = 30;
			this.CompletionCharacterEntry.Name = "CompletionCharacterEntry";
			this.CompletionCharacterEntry.Text = ":";
			this.CompletionCharacterEntry.IsEditable = true;
			this.CompletionCharacterEntry.MaxLength = 1;
			this.CompletionCharacterEntry.InvisibleChar = '●';
			this.table4.Add (this.CompletionCharacterEntry);
			global::Gtk.Table.TableChild w98 = ((global::Gtk.Table.TableChild)(this.table4 [this.CompletionCharacterEntry]));
			w98.LeftAttach = ((uint)(1));
			w98.RightAttach = ((uint)(2));
			w98.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table4.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			// Container child hbox4.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Completion Character:");
			this.hbox4.Add (this.label13);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label13]));
			w99.Position = 0;
			w99.Expand = false;
			w99.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.fixed22 = new global::Gtk.Fixed ();
			this.fixed22.Name = "fixed22";
			this.fixed22.HasWindow = false;
			this.hbox4.Add (this.fixed22);
			global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.fixed22]));
			w100.Position = 1;
			this.table4.Add (this.hbox4);
			// Container child table4.Gtk.Table+TableChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			// Container child hbox5.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Command Character:");
			this.hbox5.Add (this.label14);
			global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label14]));
			w102.Position = 0;
			w102.Expand = false;
			w102.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.fixed23 = new global::Gtk.Fixed ();
			this.fixed23.Name = "fixed23";
			this.fixed23.HasWindow = false;
			this.hbox5.Add (this.fixed23);
			global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.fixed23]));
			w103.Position = 1;
			this.table4.Add (this.hbox5);
			global::Gtk.Table.TableChild w104 = ((global::Gtk.Table.TableChild)(this.table4 [this.hbox5]));
			w104.TopAttach = ((uint)(1));
			w104.BottomAttach = ((uint)(2));
			// Container child table4.Gtk.Table+TableChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			// Container child hbox6.Gtk.Box+BoxChild
			this.label42 = new global::Gtk.Label ();
			this.label42.Name = "label42";
			this.label42.LabelProp = global::Mono.Unix.Catalog.GetString ("Command History Size:");
			this.hbox6.Add (this.label42);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label42]));
			w105.Position = 0;
			w105.Expand = false;
			w105.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.fixed24 = new global::Gtk.Fixed ();
			this.fixed24.Name = "fixed24";
			this.fixed24.HasWindow = false;
			this.hbox6.Add (this.fixed24);
			global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.fixed24]));
			w106.Position = 1;
			this.table4.Add (this.hbox6);
			global::Gtk.Table.TableChild w107 = ((global::Gtk.Table.TableChild)(this.table4 [this.hbox6]));
			w107.TopAttach = ((uint)(2));
			w107.BottomAttach = ((uint)(3));
			this.vbox7.Add (this.table4);
			global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.table4]));
			w108.Position = 0;
			w108.Expand = false;
			w108.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.BashStyleCompletionCheckButton = new global::Gtk.CheckButton ();
			this.BashStyleCompletionCheckButton.Name = "BashStyleCompletionCheckButton";
			this.BashStyleCompletionCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Bash-Style Completion");
			this.BashStyleCompletionCheckButton.DrawIndicator = true;
			this.BashStyleCompletionCheckButton.UseUnderline = true;
			this.vbox7.Add (this.BashStyleCompletionCheckButton);
			global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.BashStyleCompletionCheckButton]));
			w109.Position = 1;
			w109.Expand = false;
			w109.Fill = false;
			this.alignment7.Add (this.vbox7);
			this.frame3.Add (this.alignment7);
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("<b> Entry Field </b>");
			this.label12.UseMarkup = true;
			this.frame3.LabelWidget = this.label12;
			this.InterfaceNotebook.Add (this.frame3);
			global::Gtk.Notebook.NotebookChild w112 = ((global::Gtk.Notebook.NotebookChild)(this.InterfaceNotebook [this.frame3]));
			w112.Position = 2;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Input");
			this.InterfaceNotebook.SetTabLabel (this.frame3, this.label3);
			this.label3.ShowAll ();
			// Container child InterfaceNotebook.Gtk.Notebook+NotebookChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			// Container child vbox8.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			// Container child frame2.Gtk.Container+ContainerChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.alignment5.LeftPadding = ((uint)(12));
			// Container child alignment5.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 5;
			this.vbox9.BorderWidth = ((uint)(5));
			// Container child vbox9.Gtk.Box+BoxChild
			this.NickColorsCheckButton = new global::Gtk.CheckButton ();
			this.NickColorsCheckButton.Name = "NickColorsCheckButton";
			this.NickColorsCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Nick Colors");
			this.NickColorsCheckButton.DrawIndicator = true;
			this.NickColorsCheckButton.UseUnderline = true;
			this.vbox9.Add (this.NickColorsCheckButton);
			global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.NickColorsCheckButton]));
			w113.Position = 0;
			w113.Expand = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.frame10 = new global::Gtk.Frame ();
			this.frame10.Name = "frame10";
			// Container child frame10.Gtk.Container+ContainerChild
			this.alignment14 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment14.Name = "alignment14";
			this.alignment14.LeftPadding = ((uint)(12));
			// Container child alignment14.Gtk.Container+ContainerChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			// Container child vbox11.Gtk.Box+BoxChild
			this.TopicPositionRadioButtonTop = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Top"));
			this.TopicPositionRadioButtonTop.Name = "TopicPositionRadioButtonTop";
			this.TopicPositionRadioButtonTop.Active = true;
			this.TopicPositionRadioButtonTop.DrawIndicator = true;
			this.TopicPositionRadioButtonTop.UseUnderline = true;
			this.TopicPositionRadioButtonTop.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.TopicPositionRadioButtonTop.Remove (this.TopicPositionRadioButtonTop.Child);
			// Container child TopicPositionRadioButtonTop.Gtk.Container+ContainerChild
			this.alignment21 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			this.alignment21.Name = "alignment21";
			// Container child alignment21.Gtk.Container+ContainerChild
			this.hbox22 = new global::Gtk.HBox ();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 2;
			// Container child hbox22.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-top", global::Gtk.IconSize.Menu);
			this.hbox22.Add (this.image1);
			global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.image1]));
			w114.Position = 0;
			w114.Expand = false;
			w114.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.label52 = new global::Gtk.Label ();
			this.label52.Name = "label52";
			this.label52.LabelProp = global::Mono.Unix.Catalog.GetString ("Top");
			this.label52.UseUnderline = true;
			this.hbox22.Add (this.label52);
			global::Gtk.Box.BoxChild w115 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.label52]));
			w115.Position = 1;
			w115.Expand = false;
			w115.Fill = false;
			this.alignment21.Add (this.hbox22);
			this.TopicPositionRadioButtonTop.Add (this.alignment21);
			this.vbox11.Add (this.TopicPositionRadioButtonTop);
			global::Gtk.Box.BoxChild w118 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.TopicPositionRadioButtonTop]));
			w118.Position = 0;
			w118.Expand = false;
			w118.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.TopicPositionRadioButtonBottom = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Bottom"));
			this.TopicPositionRadioButtonBottom.Name = "TopicPositionRadioButtonBottom";
			this.TopicPositionRadioButtonBottom.DrawIndicator = true;
			this.TopicPositionRadioButtonBottom.UseUnderline = true;
			this.TopicPositionRadioButtonBottom.Group = this.TopicPositionRadioButtonTop.Group;
			this.TopicPositionRadioButtonBottom.Remove (this.TopicPositionRadioButtonBottom.Child);
			// Container child TopicPositionRadioButtonBottom.Gtk.Container+ContainerChild
			this.alignment20 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			this.alignment20.Name = "alignment20";
			// Container child alignment20.Gtk.Container+ContainerChild
			this.hbox21 = new global::Gtk.HBox ();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 2;
			// Container child hbox21.Gtk.Box+BoxChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-bottom", global::Gtk.IconSize.Menu);
			this.hbox21.Add (this.image2);
			global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.image2]));
			w119.Position = 0;
			w119.Expand = false;
			w119.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.label51 = new global::Gtk.Label ();
			this.label51.Name = "label51";
			this.label51.LabelProp = global::Mono.Unix.Catalog.GetString ("Bottom");
			this.label51.UseUnderline = true;
			this.hbox21.Add (this.label51);
			global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.label51]));
			w120.Position = 1;
			w120.Expand = false;
			w120.Fill = false;
			this.alignment20.Add (this.hbox21);
			this.TopicPositionRadioButtonBottom.Add (this.alignment20);
			this.vbox11.Add (this.TopicPositionRadioButtonBottom);
			global::Gtk.Box.BoxChild w123 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.TopicPositionRadioButtonBottom]));
			w123.Position = 1;
			w123.Expand = false;
			w123.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.TopicPositionRadioButtonNone = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("None"));
			this.TopicPositionRadioButtonNone.Name = "TopicPositionRadioButtonNone";
			this.TopicPositionRadioButtonNone.DrawIndicator = true;
			this.TopicPositionRadioButtonNone.UseUnderline = true;
			this.TopicPositionRadioButtonNone.Group = this.TopicPositionRadioButtonTop.Group;
			this.vbox11.Add (this.TopicPositionRadioButtonNone);
			global::Gtk.Box.BoxChild w124 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.TopicPositionRadioButtonNone]));
			w124.Position = 2;
			w124.Expand = false;
			w124.Fill = false;
			this.alignment14.Add (this.vbox11);
			this.frame10.Add (this.alignment14);
			this.label41 = new global::Gtk.Label ();
			this.label41.Name = "label41";
			this.label41.LabelProp = global::Mono.Unix.Catalog.GetString ("<b> Topic Position </b>");
			this.label41.UseMarkup = true;
			this.frame10.LabelWidget = this.label41;
			this.vbox9.Add (this.frame10);
			global::Gtk.Box.BoxChild w127 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.frame10]));
			w127.Position = 1;
			w127.Expand = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.frame9 = new global::Gtk.Frame ();
			this.frame9.WidthRequest = 152;
			this.frame9.HeightRequest = 96;
			this.frame9.Name = "frame9";
			// Container child frame9.Gtk.Container+ContainerChild
			this.alignment13 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment13.Name = "alignment13";
			this.alignment13.LeftPadding = ((uint)(12));
			// Container child alignment13.Gtk.Container+ContainerChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			// Container child vbox12.Gtk.Box+BoxChild
			this.UserListPositionRadioButtonLeft = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Left"));
			this.UserListPositionRadioButtonLeft.Name = "UserListPositionRadioButtonLeft";
			this.UserListPositionRadioButtonLeft.Active = true;
			this.UserListPositionRadioButtonLeft.DrawIndicator = true;
			this.UserListPositionRadioButtonLeft.UseUnderline = true;
			this.UserListPositionRadioButtonLeft.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.UserListPositionRadioButtonLeft.Remove (this.UserListPositionRadioButtonLeft.Child);
			// Container child UserListPositionRadioButtonLeft.Gtk.Container+ContainerChild
			this.alignment17 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			this.alignment17.Name = "alignment17";
			// Container child alignment17.Gtk.Container+ContainerChild
			this.hbox18 = new global::Gtk.HBox ();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 2;
			// Container child hbox18.Gtk.Box+BoxChild
			this.image3 = new global::Gtk.Image ();
			this.image3.Name = "image3";
			this.image3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-first", global::Gtk.IconSize.Menu);
			this.hbox18.Add (this.image3);
			global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.image3]));
			w128.Position = 0;
			w128.Expand = false;
			w128.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.label48 = new global::Gtk.Label ();
			this.label48.Name = "label48";
			this.label48.LabelProp = global::Mono.Unix.Catalog.GetString ("Left");
			this.label48.UseUnderline = true;
			this.hbox18.Add (this.label48);
			global::Gtk.Box.BoxChild w129 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.label48]));
			w129.Position = 1;
			w129.Expand = false;
			w129.Fill = false;
			this.alignment17.Add (this.hbox18);
			this.UserListPositionRadioButtonLeft.Add (this.alignment17);
			this.vbox12.Add (this.UserListPositionRadioButtonLeft);
			global::Gtk.Box.BoxChild w132 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.UserListPositionRadioButtonLeft]));
			w132.Position = 0;
			w132.Expand = false;
			w132.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.UserListPositionRadioButtonRight = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Right"));
			this.UserListPositionRadioButtonRight.Name = "UserListPositionRadioButtonRight";
			this.UserListPositionRadioButtonRight.DrawIndicator = true;
			this.UserListPositionRadioButtonRight.UseUnderline = true;
			this.UserListPositionRadioButtonRight.Group = this.UserListPositionRadioButtonLeft.Group;
			this.UserListPositionRadioButtonRight.Remove (this.UserListPositionRadioButtonRight.Child);
			// Container child UserListPositionRadioButtonRight.Gtk.Container+ContainerChild
			this.alignment18 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			this.alignment18.Name = "alignment18";
			// Container child alignment18.Gtk.Container+ContainerChild
			this.hbox19 = new global::Gtk.HBox ();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 2;
			// Container child hbox19.Gtk.Box+BoxChild
			this.image4 = new global::Gtk.Image ();
			this.image4.Name = "image4";
			this.image4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-last", global::Gtk.IconSize.Menu);
			this.hbox19.Add (this.image4);
			global::Gtk.Box.BoxChild w133 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.image4]));
			w133.Position = 0;
			w133.Expand = false;
			w133.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label49 = new global::Gtk.Label ();
			this.label49.Name = "label49";
			this.label49.LabelProp = global::Mono.Unix.Catalog.GetString ("Right");
			this.label49.UseUnderline = true;
			this.hbox19.Add (this.label49);
			global::Gtk.Box.BoxChild w134 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.label49]));
			w134.Position = 1;
			w134.Expand = false;
			w134.Fill = false;
			this.alignment18.Add (this.hbox19);
			this.UserListPositionRadioButtonRight.Add (this.alignment18);
			this.vbox12.Add (this.UserListPositionRadioButtonRight);
			global::Gtk.Box.BoxChild w137 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.UserListPositionRadioButtonRight]));
			w137.Position = 1;
			w137.Expand = false;
			w137.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.UserListPositionRadioButtonNone = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("None"));
			this.UserListPositionRadioButtonNone.Name = "UserListPositionRadioButtonNone";
			this.UserListPositionRadioButtonNone.DrawIndicator = true;
			this.UserListPositionRadioButtonNone.UseUnderline = true;
			this.UserListPositionRadioButtonNone.Group = this.UserListPositionRadioButtonLeft.Group;
			this.vbox12.Add (this.UserListPositionRadioButtonNone);
			global::Gtk.Box.BoxChild w138 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.UserListPositionRadioButtonNone]));
			w138.Position = 2;
			w138.Expand = false;
			w138.Fill = false;
			this.alignment13.Add (this.vbox12);
			this.frame9.Add (this.alignment13);
			this.label38 = new global::Gtk.Label ();
			this.label38.Name = "label38";
			this.label38.LabelProp = global::Mono.Unix.Catalog.GetString ("<b> User List Position </b>");
			this.label38.UseMarkup = true;
			this.frame9.LabelWidget = this.label38;
			this.vbox9.Add (this.frame9);
			global::Gtk.Box.BoxChild w141 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.frame9]));
			w141.Position = 2;
			w141.Expand = false;
			this.alignment5.Add (this.vbox9);
			this.frame2.Add (this.alignment5);
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("<b> Channel </b>");
			this.label10.UseMarkup = true;
			this.frame2.LabelWidget = this.label10;
			this.vbox8.Add (this.frame2);
			global::Gtk.Box.BoxChild w144 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.frame2]));
			w144.Position = 0;
			w144.Expand = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.frame11 = new global::Gtk.Frame ();
			this.frame11.Name = "frame11";
			// Container child frame11.Gtk.Container+ContainerChild
			this.alignment27 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment27.Name = "alignment27";
			this.alignment27.LeftPadding = ((uint)(12));
			// Container child alignment27.Gtk.Container+ContainerChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.BorderWidth = ((uint)(5));
			// Container child vbox13.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			// Container child vbox14.Gtk.Box+BoxChild
			this.label62 = new global::Gtk.Label ();
			this.label62.Name = "label62";
			this.label62.Xalign = 0F;
			this.label62.LabelProp = global::Mono.Unix.Catalog.GetString ("Highlight words:");
			this.vbox14.Add (this.label62);
			global::Gtk.Box.BoxChild w145 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.label62]));
			w145.Position = 0;
			w145.Expand = false;
			w145.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.scrolledwindow4 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow4.Name = "scrolledwindow4";
			this.scrolledwindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow4.Gtk.Container+ContainerChild
			this.HighlightWordsTextView = new global::Gtk.TextView ();
			this.HighlightWordsTextView.Sensitive = false;
			this.HighlightWordsTextView.Name = "HighlightWordsTextView";
			this.scrolledwindow4.Add (this.HighlightWordsTextView);
			this.vbox14.Add (this.scrolledwindow4);
			global::Gtk.Box.BoxChild w147 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.scrolledwindow4]));
			w147.Position = 1;
			this.vbox13.Add (this.vbox14);
			global::Gtk.Box.BoxChild w148 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.vbox14]));
			w148.Position = 0;
			// Container child vbox13.Gtk.Box+BoxChild
			this.BeepOnHighlightCheckButton = new global::Gtk.CheckButton ();
			this.BeepOnHighlightCheckButton.Name = "BeepOnHighlightCheckButton";
			this.BeepOnHighlightCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Beep on highlight");
			this.BeepOnHighlightCheckButton.DrawIndicator = true;
			this.BeepOnHighlightCheckButton.UseUnderline = true;
			this.vbox13.Add (this.BeepOnHighlightCheckButton);
			global::Gtk.Box.BoxChild w149 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.BeepOnHighlightCheckButton]));
			w149.Position = 1;
			w149.Expand = false;
			w149.Fill = false;
			this.alignment27.Add (this.vbox13);
			this.frame11.Add (this.alignment27);
			this.label61 = new global::Gtk.Label ();
			this.label61.Name = "label61";
			this.label61.LabelProp = global::Mono.Unix.Catalog.GetString ("<b> Highlighting </b>");
			this.label61.UseMarkup = true;
			this.frame11.LabelWidget = this.label61;
			this.vbox8.Add (this.frame11);
			global::Gtk.Box.BoxChild w152 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.frame11]));
			w152.Position = 1;
			this.InterfaceNotebook.Add (this.vbox8);
			global::Gtk.Notebook.NotebookChild w153 = ((global::Gtk.Notebook.NotebookChild)(this.InterfaceNotebook [this.vbox8]));
			w153.Position = 3;
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Output");
			this.InterfaceNotebook.SetTabLabel (this.vbox8, this.label4);
			this.label4.ShowAll ();
			this.Notebook.Add (this.InterfaceNotebook);
			global::Gtk.Notebook.NotebookChild w154 = ((global::Gtk.Notebook.NotebookChild)(this.Notebook [this.InterfaceNotebook]));
			w154.Position = 1;
			// Notebook tab
			this.label45 = new global::Gtk.Label ();
			this.label45.Name = "label45";
			this.label45.LabelProp = global::Mono.Unix.Catalog.GetString ("_Interface");
			this.label45.UseUnderline = true;
			this.Notebook.SetTabLabel (this.InterfaceNotebook, this.label45);
			this.label45.ShowAll ();
			// Container child Notebook.Gtk.Notebook+NotebookChild
			this.hbox27 = new global::Gtk.HBox ();
			this.hbox27.Name = "hbox27";
			this.hbox27.BorderWidth = ((uint)(5));
			// Container child hbox27.Gtk.Box+BoxChild
			this.scrolledwindow3 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow3.Name = "scrolledwindow3";
			this.scrolledwindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow3.Gtk.Container+ContainerChild
			this.ServersTreeView = new global::Gtk.TreeView ();
			this.ServersTreeView.Name = "ServersTreeView";
			this.scrolledwindow3.Add (this.ServersTreeView);
			this.hbox27.Add (this.scrolledwindow3);
			global::Gtk.Box.BoxChild w156 = ((global::Gtk.Box.BoxChild)(this.hbox27 [this.scrolledwindow3]));
			w156.Position = 0;
			// Container child hbox27.Gtk.Box+BoxChild
			this.vbuttonbox1 = new global::Gtk.VButtonBox ();
			this.vbuttonbox1.Name = "vbuttonbox1";
			this.vbuttonbox1.BorderWidth = ((uint)(5));
			this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.ServersAddButton = new global::Gtk.Button ();
			this.ServersAddButton.Name = "ServersAddButton";
			this.ServersAddButton.UseStock = true;
			this.ServersAddButton.UseUnderline = true;
			this.ServersAddButton.Label = "gtk-add";
			this.vbuttonbox1.Add (this.ServersAddButton);
			global::Gtk.ButtonBox.ButtonBoxChild w157 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.ServersAddButton]));
			w157.Expand = false;
			w157.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.ServersEditButton = new global::Gtk.Button ();
			this.ServersEditButton.Name = "ServersEditButton";
			this.ServersEditButton.UseStock = true;
			this.ServersEditButton.UseUnderline = true;
			this.ServersEditButton.Label = "gtk-edit";
			this.vbuttonbox1.Add (this.ServersEditButton);
			global::Gtk.ButtonBox.ButtonBoxChild w158 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.ServersEditButton]));
			w158.Position = 1;
			w158.Expand = false;
			w158.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.ServersRemoveButton = new global::Gtk.Button ();
			this.ServersRemoveButton.Name = "ServersRemoveButton";
			this.ServersRemoveButton.UseStock = true;
			this.ServersRemoveButton.UseUnderline = true;
			this.ServersRemoveButton.Label = "gtk-remove";
			this.vbuttonbox1.Add (this.ServersRemoveButton);
			global::Gtk.ButtonBox.ButtonBoxChild w159 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.ServersRemoveButton]));
			w159.Position = 2;
			w159.Expand = false;
			w159.Fill = false;
			this.hbox27.Add (this.vbuttonbox1);
			global::Gtk.Box.BoxChild w160 = ((global::Gtk.Box.BoxChild)(this.hbox27 [this.vbuttonbox1]));
			w160.Position = 1;
			w160.Expand = false;
			this.Notebook.Add (this.hbox27);
			global::Gtk.Notebook.NotebookChild w161 = ((global::Gtk.Notebook.NotebookChild)(this.Notebook [this.hbox27]));
			w161.Position = 2;
			// Notebook tab
			this.label57 = new global::Gtk.Label ();
			this.label57.Name = "label57";
			this.label57.LabelProp = global::Mono.Unix.Catalog.GetString ("_Servers");
			this.label57.UseUnderline = true;
			this.Notebook.SetTabLabel (this.hbox27, this.label57);
			this.label57.ShowAll ();
			// Container child Notebook.Gtk.Notebook+NotebookChild
			this.vbox15 = new global::Gtk.VBox ();
			this.vbox15.Name = "vbox15";
			this.vbox15.BorderWidth = ((uint)(5));
			// Container child vbox15.Gtk.Box+BoxChild
			this.frame12 = new global::Gtk.Frame ();
			this.frame12.Name = "frame12";
			// Container child frame12.Gtk.Container+ContainerChild
			this.alignment28 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment28.Name = "alignment28";
			this.alignment28.LeftPadding = ((uint)(12));
			// Container child alignment28.Gtk.Container+ContainerChild
			this.vbox16 = new global::Gtk.VBox ();
			this.vbox16.Name = "vbox16";
			// Container child vbox16.Gtk.Box+BoxChild
			this.scrolledwindow5 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow5.Name = "scrolledwindow5";
			this.scrolledwindow5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow5.Gtk.Container+ContainerChild
			this.ChannelFiltersTreeView = new global::Gtk.TreeView ();
			this.ChannelFiltersTreeView.Name = "ChannelFiltersTreeView";
			this.scrolledwindow5.Add (this.ChannelFiltersTreeView);
			this.vbox16.Add (this.scrolledwindow5);
			global::Gtk.Box.BoxChild w163 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.scrolledwindow5]));
			w163.Position = 0;
			// Container child vbox16.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.ChannelFiltersAddButton = new global::Gtk.Button ();
			this.ChannelFiltersAddButton.Sensitive = false;
			this.ChannelFiltersAddButton.Name = "ChannelFiltersAddButton";
			this.ChannelFiltersAddButton.UseStock = true;
			this.ChannelFiltersAddButton.UseUnderline = true;
			this.ChannelFiltersAddButton.Label = "gtk-add";
			this.hbuttonbox1.Add (this.ChannelFiltersAddButton);
			global::Gtk.ButtonBox.ButtonBoxChild w164 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.ChannelFiltersAddButton]));
			w164.Expand = false;
			w164.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.ChannelFiltersRemoveButton = new global::Gtk.Button ();
			this.ChannelFiltersRemoveButton.Sensitive = false;
			this.ChannelFiltersRemoveButton.Name = "ChannelFiltersRemoveButton";
			this.ChannelFiltersRemoveButton.UseStock = true;
			this.ChannelFiltersRemoveButton.UseUnderline = true;
			this.ChannelFiltersRemoveButton.Label = "gtk-remove";
			this.hbuttonbox1.Add (this.ChannelFiltersRemoveButton);
			global::Gtk.ButtonBox.ButtonBoxChild w165 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.ChannelFiltersRemoveButton]));
			w165.Position = 1;
			w165.Expand = false;
			w165.Fill = false;
			this.vbox16.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w166 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.hbuttonbox1]));
			w166.Position = 1;
			w166.Expand = false;
			this.alignment28.Add (this.vbox16);
			this.frame12.Add (this.alignment28);
			this.label64 = new global::Gtk.Label ();
			this.label64.Name = "label64";
			this.label64.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Channel Filters</b>");
			this.label64.UseMarkup = true;
			this.frame12.LabelWidget = this.label64;
			this.vbox15.Add (this.frame12);
			global::Gtk.Box.BoxChild w169 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.frame12]));
			w169.Position = 0;
			// Container child vbox15.Gtk.Box+BoxChild
			this.frame13 = new global::Gtk.Frame ();
			this.frame13.Sensitive = false;
			this.frame13.Name = "frame13";
			// Container child frame13.Gtk.Container+ContainerChild
			this.alignment29 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment29.Name = "alignment29";
			this.alignment29.LeftPadding = ((uint)(12));
			this.frame13.Add (this.alignment29);
			this.label65 = new global::Gtk.Label ();
			this.label65.Name = "label65";
			this.label65.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>User Filters</b>");
			this.label65.UseMarkup = true;
			this.frame13.LabelWidget = this.label65;
			this.vbox15.Add (this.frame13);
			global::Gtk.Box.BoxChild w171 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.frame13]));
			w171.Position = 1;
			this.Notebook.Add (this.vbox15);
			global::Gtk.Notebook.NotebookChild w172 = ((global::Gtk.Notebook.NotebookChild)(this.Notebook [this.vbox15]));
			w172.Position = 3;
			// Notebook tab
			this.label63 = new global::Gtk.Label ();
			this.label63.Name = "label63";
			this.label63.LabelProp = global::Mono.Unix.Catalog.GetString ("_Filters");
			this.label63.UseUnderline = true;
			this.Notebook.SetTabLabel (this.vbox15, this.label63);
			this.label63.ShowAll ();
			this.hbox1.Add (this.Notebook);
			global::Gtk.Box.BoxChild w173 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.Notebook]));
			w173.Position = 1;
			w1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w174 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox1]));
			w174.Position = 0;
			// Internal child Smuxi.Frontend.Gnome.SteticPreferencesDialog.ActionArea
			global::Gtk.HButtonBox w175 = this.ActionArea;
			w175.Name = "dialog-action_area1";
			w175.Spacing = 6;
			w175.BorderWidth = ((uint)(5));
			w175.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog-action_area1.Gtk.ButtonBox+ButtonBoxChild
			this.CancelButton = new global::Gtk.Button ();
			this.CancelButton.Name = "CancelButton";
			this.CancelButton.UseStock = true;
			this.CancelButton.UseUnderline = true;
			this.CancelButton.Label = "gtk-cancel";
			this.AddActionWidget (this.CancelButton, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w176 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w175 [this.CancelButton]));
			w176.Expand = false;
			w176.Fill = false;
			// Container child dialog-action_area1.Gtk.ButtonBox+ButtonBoxChild
			this.ApplyButton = new global::Gtk.Button ();
			this.ApplyButton.Sensitive = false;
			this.ApplyButton.Name = "ApplyButton";
			this.ApplyButton.UseStock = true;
			this.ApplyButton.UseUnderline = true;
			this.ApplyButton.Label = "gtk-apply";
			this.AddActionWidget (this.ApplyButton, -10);
			global::Gtk.ButtonBox.ButtonBoxChild w177 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w175 [this.ApplyButton]));
			w177.Position = 1;
			w177.Expand = false;
			w177.Fill = false;
			// Container child dialog-action_area1.Gtk.ButtonBox+ButtonBoxChild
			this.OKButton = new global::Gtk.Button ();
			this.OKButton.Name = "OKButton";
			this.OKButton.UseStock = true;
			this.OKButton.UseUnderline = true;
			this.OKButton.Label = "gtk-ok";
			this.AddActionWidget (this.OKButton, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w178 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w175 [this.OKButton]));
			w178.Position = 2;
			w178.Expand = false;
			w178.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 526;
			this.DefaultHeight = 579;
			this.label44.MnemonicWidget = this.Notebook;
			this.label45.MnemonicWidget = this.Notebook;
			this.label57.MnemonicWidget = this.Notebook;
			this.label63.MnemonicWidget = this.Notebook;
			this.Show ();
			this.EncodingComboBox.Changed += new global::System.EventHandler (this._OnChanged);
			this.ConnectionUsernameEntry.Changed += new global::System.EventHandler (this._OnChanged);
			this.ConnectionRealnameEntry.Changed += new global::System.EventHandler (this._OnChanged);
			this.ConnectionNicknamesEntry.Changed += new global::System.EventHandler (this._OnChanged);
			this.TimestampFormatEntry.Changed += new global::System.EventHandler (this._OnChanged);
			this.EngineBufferLinesSpinButton.Changed += new global::System.EventHandler (this._OnChanged);
			this.BufferLinesSpinButton.Changed += new global::System.EventHandler (this._OnChanged);
			this.TabPositionRadioButtonBottom.Toggled += new global::System.EventHandler (this._OnChanged);
			this.TabPositionRadioButtonLeft.Toggled += new global::System.EventHandler (this._OnChanged);
			this.TabPositionRadioButtonRight.Toggled += new global::System.EventHandler (this._OnChanged);
			this.TabPositionRadioButtonNone.Toggled += new global::System.EventHandler (this._OnChanged);
			this.NoActivityColorButton.ColorSet += new global::System.EventHandler (this._OnChanged);
			this.ModeColorButton.ColorSet += new global::System.EventHandler (this._OnChanged);
			this.ActivityColorButton.ColorSet += new global::System.EventHandler (this._OnChanged);
			this.CompletionCharacterEntry.Changed += new global::System.EventHandler (this._OnChanged);
			this.CommandHistorySizeSpinButton.Changed += new global::System.EventHandler (this._OnChanged);
			this.CommandCharacterEntry.Changed += new global::System.EventHandler (this._OnChanged);
			this.TopicPositionRadioButtonTop.Toggled += new global::System.EventHandler (this._OnChanged);
			this.TopicPositionRadioButtonBottom.Toggled += new global::System.EventHandler (this._OnChanged);
			this.TopicPositionRadioButtonNone.Toggled += new global::System.EventHandler (this._OnChanged);
			this.UserListPositionRadioButtonLeft.Toggled += new global::System.EventHandler (this._OnChanged);
			this.UserListPositionRadioButtonRight.Toggled += new global::System.EventHandler (this._OnChanged);
			this.UserListPositionRadioButtonNone.Toggled += new global::System.EventHandler (this._OnChanged);
		}
	}
}
