// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Smuxi.Frontend.Gnome {
    
    
    public partial class QuickConnectDialog {
        
        private Gtk.VBox vbox16;
        
        private Gtk.Table table2;
        
        private Gtk.Entry f_PasswordEntry;
        
        private Gtk.ComboBox f_ProtocolComboBox;
        
        private Gtk.Entry f_UsernameEntry;
        
        private Gtk.HBox hbox10;
        
        private Gtk.Entry f_HostnameEntry;
        
        private Gtk.HBox hbox11;
        
        private Gtk.Label label20;
        
        private Gtk.SpinButton f_PortSpinButton;
        
        private Gtk.Label label11;
        
        private Gtk.Label label21;
        
        private Gtk.Label label22;
        
        private Gtk.Label label5;
        
        private Gtk.Button f_CancelButton;
        
        private Gtk.Button f_ConnectButton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Smuxi.Frontend.Gnome.QuickConnectDialog
            this.Name = "Smuxi.Frontend.Gnome.QuickConnectDialog";
            this.Title = Mono.Unix.Catalog.GetString("smuxi - Quick Connect");
            this.TypeHint = ((Gdk.WindowTypeHint)(1));
            this.BorderWidth = ((uint)(5));
            this.Resizable = false;
            this.AllowGrow = false;
            // Internal child Smuxi.Frontend.Gnome.QuickConnectDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog-vbox2";
            w1.Spacing = 5;
            w1.BorderWidth = ((uint)(2));
            // Container child dialog-vbox2.Gtk.Box+BoxChild
            this.vbox16 = new Gtk.VBox();
            this.vbox16.Name = "vbox16";
            // Container child vbox16.Gtk.Box+BoxChild
            this.table2 = new Gtk.Table(((uint)(4)), ((uint)(2)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(5));
            this.table2.ColumnSpacing = ((uint)(5));
            // Container child table2.Gtk.Table+TableChild
            this.f_PasswordEntry = new Gtk.Entry();
            this.f_PasswordEntry.Name = "f_PasswordEntry";
            this.f_PasswordEntry.IsEditable = true;
            this.f_PasswordEntry.InvisibleChar = '●';
            this.table2.Add(this.f_PasswordEntry);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table2[this.f_PasswordEntry]));
            w2.TopAttach = ((uint)(3));
            w2.BottomAttach = ((uint)(4));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            // Container child table2.Gtk.Table+TableChild
            this.f_ProtocolComboBox = new Gtk.ComboBox();
            this.f_ProtocolComboBox.Name = "f_ProtocolComboBox";
            this.table2.Add(this.f_ProtocolComboBox);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table2[this.f_ProtocolComboBox]));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            // Container child table2.Gtk.Table+TableChild
            this.f_UsernameEntry = new Gtk.Entry();
            this.f_UsernameEntry.Name = "f_UsernameEntry";
            this.f_UsernameEntry.IsEditable = true;
            this.f_UsernameEntry.InvisibleChar = '●';
            this.table2.Add(this.f_UsernameEntry);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table2[this.f_UsernameEntry]));
            w4.TopAttach = ((uint)(2));
            w4.BottomAttach = ((uint)(3));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            // Container child table2.Gtk.Table+TableChild
            this.hbox10 = new Gtk.HBox();
            this.hbox10.Name = "hbox10";
            // Container child hbox10.Gtk.Box+BoxChild
            this.f_HostnameEntry = new Gtk.Entry();
            this.f_HostnameEntry.Name = "f_HostnameEntry";
            this.f_HostnameEntry.IsEditable = true;
            this.f_HostnameEntry.InvisibleChar = '●';
            this.hbox10.Add(this.f_HostnameEntry);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox10[this.f_HostnameEntry]));
            w5.Position = 0;
            // Container child hbox10.Gtk.Box+BoxChild
            this.hbox11 = new Gtk.HBox();
            this.hbox11.Name = "hbox11";
            this.hbox11.Spacing = 5;
            // Container child hbox11.Gtk.Box+BoxChild
            this.label20 = new Gtk.Label();
            this.label20.Name = "label20";
            this.label20.LabelProp = Mono.Unix.Catalog.GetString("_Port:");
            this.label20.UseUnderline = true;
            this.hbox11.Add(this.label20);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox11[this.label20]));
            w6.Position = 0;
            // Container child hbox11.Gtk.Box+BoxChild
            this.f_PortSpinButton = new Gtk.SpinButton(0, 65535, 1);
            this.f_PortSpinButton.Name = "f_PortSpinButton";
            this.f_PortSpinButton.Adjustment.PageIncrement = 10;
            this.f_PortSpinButton.Adjustment.PageSize = 10;
            this.f_PortSpinButton.ClimbRate = 1;
            this.f_PortSpinButton.Numeric = true;
            this.hbox11.Add(this.f_PortSpinButton);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox11[this.f_PortSpinButton]));
            w7.Position = 1;
            this.hbox10.Add(this.hbox11);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox10[this.hbox11]));
            w8.Position = 1;
            this.table2.Add(this.hbox10);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table2[this.hbox10]));
            w9.TopAttach = ((uint)(1));
            w9.BottomAttach = ((uint)(2));
            w9.LeftAttach = ((uint)(1));
            w9.RightAttach = ((uint)(2));
            // Container child table2.Gtk.Table+TableChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.Xalign = 0F;
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("_Hostname:");
            this.label11.UseUnderline = true;
            this.table2.Add(this.label11);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table2[this.label11]));
            w10.TopAttach = ((uint)(1));
            w10.BottomAttach = ((uint)(2));
            // Container child table2.Gtk.Table+TableChild
            this.label21 = new Gtk.Label();
            this.label21.Name = "label21";
            this.label21.Xalign = 0F;
            this.label21.LabelProp = Mono.Unix.Catalog.GetString("_Username:");
            this.label21.UseUnderline = true;
            this.table2.Add(this.label21);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table2[this.label21]));
            w11.TopAttach = ((uint)(2));
            w11.BottomAttach = ((uint)(3));
            // Container child table2.Gtk.Table+TableChild
            this.label22 = new Gtk.Label();
            this.label22.Name = "label22";
            this.label22.Xalign = 0F;
            this.label22.LabelProp = Mono.Unix.Catalog.GetString("_Password:");
            this.label22.UseUnderline = true;
            this.table2.Add(this.label22);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table2[this.label22]));
            w12.TopAttach = ((uint)(3));
            w12.BottomAttach = ((uint)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xalign = 0F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("_Protocol:");
            this.label5.UseUnderline = true;
            this.table2.Add(this.label5);
            this.vbox16.Add(this.table2);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox16[this.table2]));
            w14.Position = 0;
            w14.Expand = false;
            w1.Add(this.vbox16);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(w1[this.vbox16]));
            w15.Position = 0;
            // Internal child Smuxi.Frontend.Gnome.QuickConnectDialog.ActionArea
            Gtk.HButtonBox w16 = this.ActionArea;
            w16.Name = "dialog-action_area2";
            w16.Spacing = 6;
            w16.BorderWidth = ((uint)(5));
            w16.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog-action_area2.Gtk.ButtonBox+ButtonBoxChild
            this.f_CancelButton = new Gtk.Button();
            this.f_CancelButton.Name = "f_CancelButton";
            this.f_CancelButton.UseStock = true;
            this.f_CancelButton.UseUnderline = true;
            this.f_CancelButton.Label = "gtk-cancel";
            this.AddActionWidget(this.f_CancelButton, -6);
            // Container child dialog-action_area2.Gtk.ButtonBox+ButtonBoxChild
            this.f_ConnectButton = new Gtk.Button();
            this.f_ConnectButton.Name = "f_ConnectButton";
            this.f_ConnectButton.UseStock = true;
            this.f_ConnectButton.UseUnderline = true;
            this.f_ConnectButton.Label = "gtk-connect";
            this.AddActionWidget(this.f_ConnectButton, -5);
            Gtk.ButtonBox.ButtonBoxChild w18 = ((Gtk.ButtonBox.ButtonBoxChild)(w16[this.f_ConnectButton]));
            w18.Position = 1;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 372;
            this.DefaultHeight = 412;
            this.label20.MnemonicWidget = this.f_PortSpinButton;
            this.label11.MnemonicWidget = this.f_HostnameEntry;
            this.label21.MnemonicWidget = this.f_UsernameEntry;
            this.label22.MnemonicWidget = this.f_PasswordEntry;
            this.label5.MnemonicWidget = this.f_ProtocolComboBox;
            this.Show();
            this.f_ConnectButton.Clicked += new System.EventHandler(this.OnConnectButtonClicked);
        }
    }
}
