
// This file has been generated by the GUI designer. Do not modify.
namespace Smuxi.Frontend.Gnome
{
	public partial class JoinWidget
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.Entry f_ChatEntry;
		private global::Gtk.Label label1;
		private global::Gtk.ComboBox f_NetworkComboBox;
		private global::Gtk.Button f_JoinButton;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Smuxi.Frontend.Gnome.JoinWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Smuxi.Frontend.Gnome.JoinWidget";
			// Container child Smuxi.Frontend.Gnome.JoinWidget.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.f_ChatEntry = new global::Gtk.Entry ();
			this.f_ChatEntry.CanFocus = true;
			this.f_ChatEntry.Name = "f_ChatEntry";
			this.f_ChatEntry.IsEditable = true;
			this.f_ChatEntry.InvisibleChar = '•';
			this.hbox1.Add (this.f_ChatEntry);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.f_ChatEntry]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = "@";
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.f_NetworkComboBox = global::Gtk.ComboBox.NewText ();
			this.f_NetworkComboBox.Name = "f_NetworkComboBox";
			this.hbox1.Add (this.f_NetworkComboBox);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.f_NetworkComboBox]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.f_JoinButton = new global::Gtk.Button ();
			this.f_JoinButton.CanFocus = true;
			this.f_JoinButton.Name = "f_JoinButton";
			this.f_JoinButton.UseUnderline = true;
			this.f_JoinButton.Label = global::Mono.Unix.Catalog.GetString ("Join Chat");
			this.hbox1.Add (this.f_JoinButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.f_JoinButton]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
