// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Smuxi.Frontend.Gnome {
    
    
    public partial class ConnectDialog {
        
        private Gtk.ScrolledWindow f_ScrolledWindow;
        
        private Gtk.TreeView f_TreeView;
        
        private Gtk.Button f_CancelButton;
        
        private Gtk.Button f_ConnectButton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Smuxi.Frontend.Gnome.ConnectDialog
            this.Name = "Smuxi.Frontend.Gnome.ConnectDialog";
            this.Title = Mono.Unix.Catalog.GetString("smuxi - Connect");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child Smuxi.Frontend.Gnome.ConnectDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.f_ScrolledWindow = new Gtk.ScrolledWindow();
            this.f_ScrolledWindow.Name = "f_ScrolledWindow";
            this.f_ScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child f_ScrolledWindow.Gtk.Container+ContainerChild
            this.f_TreeView = new Gtk.TreeView();
            this.f_TreeView.CanFocus = true;
            this.f_TreeView.Name = "f_TreeView";
            this.f_TreeView.HeadersClickable = true;
            this.f_ScrolledWindow.Add(this.f_TreeView);
            w1.Add(this.f_ScrolledWindow);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(w1[this.f_ScrolledWindow]));
            w3.Position = 0;
            // Internal child Smuxi.Frontend.Gnome.ConnectDialog.ActionArea
            Gtk.HButtonBox w4 = this.ActionArea;
            w4.Name = "dialog1_ActionArea";
            w4.Spacing = 6;
            w4.BorderWidth = ((uint)(5));
            w4.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.f_CancelButton = new Gtk.Button();
            this.f_CancelButton.CanDefault = true;
            this.f_CancelButton.CanFocus = true;
            this.f_CancelButton.Name = "f_CancelButton";
            this.f_CancelButton.UseStock = true;
            this.f_CancelButton.UseUnderline = true;
            this.f_CancelButton.Label = "gtk-cancel";
            this.AddActionWidget(this.f_CancelButton, -6);
            Gtk.ButtonBox.ButtonBoxChild w5 = ((Gtk.ButtonBox.ButtonBoxChild)(w4[this.f_CancelButton]));
            w5.Expand = false;
            w5.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.f_ConnectButton = new Gtk.Button();
            this.f_ConnectButton.CanDefault = true;
            this.f_ConnectButton.CanFocus = true;
            this.f_ConnectButton.Name = "f_ConnectButton";
            this.f_ConnectButton.UseStock = true;
            this.f_ConnectButton.UseUnderline = true;
            this.f_ConnectButton.Label = "gtk-connect";
            this.AddActionWidget(this.f_ConnectButton, -5);
            Gtk.ButtonBox.ButtonBoxChild w6 = ((Gtk.ButtonBox.ButtonBoxChild)(w4[this.f_ConnectButton]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
            this.f_ConnectButton.Clicked += new System.EventHandler(this.OnConnectButtonClicked);
        }
    }
}
