// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Smuxi.Frontend.Gnome {
    
    
    public partial class EngineAssistantCredentialsWidget {
        
        private Gtk.VBox vbox12;
        
        private Gtk.VBox vbox13;
        
        private Gtk.Label label6;
        
        private Gtk.Entry f_SshUsernameEntry;
        
        private Gtk.Label label9;
        
        private Gtk.VBox vbox16;
        
        private Gtk.Label label12;
        
        private Gtk.Entry f_UsernameEntry1;
        
        private Gtk.Label label13;
        
        private Gtk.VBox vbox14;
        
        private Gtk.Label label7;
        
        private Gtk.Entry f_PasswordEntry;
        
        private Gtk.Label label10;
        
        private Gtk.VBox vbox15;
        
        private Gtk.Label label8;
        
        private Gtk.Entry f_VerifyPasswordEntry;
        
        private Gtk.Label label11;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Smuxi.Frontend.Gnome.EngineAssistantCredentialsWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "Smuxi.Frontend.Gnome.EngineAssistantCredentialsWidget";
            // Container child Smuxi.Frontend.Gnome.EngineAssistantCredentialsWidget.Gtk.Container+ContainerChild
            this.vbox12 = new Gtk.VBox();
            this.vbox12.Name = "vbox12";
            this.vbox12.Spacing = 10;
            this.vbox12.BorderWidth = ((uint)(5));
            // Container child vbox12.Gtk.Box+BoxChild
            this.vbox13 = new Gtk.VBox();
            this.vbox13.Name = "vbox13";
            this.vbox13.Spacing = 6;
            // Container child vbox13.Gtk.Box+BoxChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.Xalign = 0F;
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("_SSH Username: (optional)");
            this.label6.UseUnderline = true;
            this.vbox13.Add(this.label6);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox13[this.label6]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox13.Gtk.Box+BoxChild
            this.f_SshUsernameEntry = new Gtk.Entry();
            this.f_SshUsernameEntry.CanFocus = true;
            this.f_SshUsernameEntry.Name = "f_SshUsernameEntry";
            this.f_SshUsernameEntry.IsEditable = true;
            this.f_SshUsernameEntry.InvisibleChar = '●';
            this.vbox13.Add(this.f_SshUsernameEntry);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox13[this.f_SshUsernameEntry]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox13.Gtk.Box+BoxChild
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.Xpad = 50;
            this.label9.Xalign = 0F;
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("<span size=\"small\">Username which will be used to log into the SSH server</span>");
            this.label9.UseMarkup = true;
            this.vbox13.Add(this.label9);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox13[this.label9]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            this.vbox12.Add(this.vbox13);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox12[this.vbox13]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox12.Gtk.Box+BoxChild
            this.vbox16 = new Gtk.VBox();
            this.vbox16.Name = "vbox16";
            this.vbox16.Spacing = 6;
            // Container child vbox16.Gtk.Box+BoxChild
            this.label12 = new Gtk.Label();
            this.label12.Name = "label12";
            this.label12.Xalign = 0F;
            this.label12.LabelProp = Mono.Unix.Catalog.GetString("_Username:");
            this.label12.UseUnderline = true;
            this.vbox16.Add(this.label12);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox16[this.label12]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox16.Gtk.Box+BoxChild
            this.f_UsernameEntry1 = new Gtk.Entry();
            this.f_UsernameEntry1.CanFocus = true;
            this.f_UsernameEntry1.Name = "f_UsernameEntry1";
            this.f_UsernameEntry1.IsEditable = true;
            this.f_UsernameEntry1.InvisibleChar = '●';
            this.vbox16.Add(this.f_UsernameEntry1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox16[this.f_UsernameEntry1]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox16.Gtk.Box+BoxChild
            this.label13 = new Gtk.Label();
            this.label13.Name = "label13";
            this.label13.Xpad = 50;
            this.label13.Xalign = 0F;
            this.label13.LabelProp = Mono.Unix.Catalog.GetString("<span size=\"small\">Username which will be used to log into the Smuxi server</span>");
            this.label13.UseMarkup = true;
            this.vbox16.Add(this.label13);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox16[this.label13]));
            w7.Position = 2;
            w7.Expand = false;
            w7.Fill = false;
            this.vbox12.Add(this.vbox16);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox12[this.vbox16]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            // Container child vbox12.Gtk.Box+BoxChild
            this.vbox14 = new Gtk.VBox();
            this.vbox14.Name = "vbox14";
            this.vbox14.Spacing = 6;
            // Container child vbox14.Gtk.Box+BoxChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.Xalign = 0F;
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("_Password:");
            this.label7.UseUnderline = true;
            this.vbox14.Add(this.label7);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox14[this.label7]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox14.Gtk.Box+BoxChild
            this.f_PasswordEntry = new Gtk.Entry();
            this.f_PasswordEntry.CanFocus = true;
            this.f_PasswordEntry.Name = "f_PasswordEntry";
            this.f_PasswordEntry.IsEditable = true;
            this.f_PasswordEntry.Visibility = false;
            this.f_PasswordEntry.InvisibleChar = '●';
            this.vbox14.Add(this.f_PasswordEntry);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox14[this.f_PasswordEntry]));
            w10.Position = 1;
            w10.Expand = false;
            w10.Fill = false;
            // Container child vbox14.Gtk.Box+BoxChild
            this.label10 = new Gtk.Label();
            this.label10.Name = "label10";
            this.label10.Xpad = 50;
            this.label10.Xalign = 0F;
            this.label10.LabelProp = Mono.Unix.Catalog.GetString("<span size=\"small\">Password of the user</span>");
            this.label10.UseMarkup = true;
            this.vbox14.Add(this.label10);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox14[this.label10]));
            w11.Position = 2;
            w11.Expand = false;
            w11.Fill = false;
            this.vbox12.Add(this.vbox14);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox12[this.vbox14]));
            w12.Position = 2;
            w12.Expand = false;
            w12.Fill = false;
            // Container child vbox12.Gtk.Box+BoxChild
            this.vbox15 = new Gtk.VBox();
            this.vbox15.Name = "vbox15";
            this.vbox15.Spacing = 6;
            // Container child vbox15.Gtk.Box+BoxChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.Xalign = 0F;
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("_Verify Password:");
            this.label8.UseUnderline = true;
            this.vbox15.Add(this.label8);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox15[this.label8]));
            w13.Position = 0;
            w13.Expand = false;
            w13.Fill = false;
            // Container child vbox15.Gtk.Box+BoxChild
            this.f_VerifyPasswordEntry = new Gtk.Entry();
            this.f_VerifyPasswordEntry.CanFocus = true;
            this.f_VerifyPasswordEntry.Name = "f_VerifyPasswordEntry";
            this.f_VerifyPasswordEntry.IsEditable = true;
            this.f_VerifyPasswordEntry.Visibility = false;
            this.f_VerifyPasswordEntry.InvisibleChar = '●';
            this.vbox15.Add(this.f_VerifyPasswordEntry);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox15[this.f_VerifyPasswordEntry]));
            w14.Position = 1;
            w14.Expand = false;
            w14.Fill = false;
            // Container child vbox15.Gtk.Box+BoxChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.Xpad = 50;
            this.label11.Xalign = 0F;
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("<span size=\"small\">Repeat the password for verification</span>");
            this.label11.UseMarkup = true;
            this.vbox15.Add(this.label11);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox15[this.label11]));
            w15.Position = 2;
            w15.Expand = false;
            w15.Fill = false;
            this.vbox12.Add(this.vbox15);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox12[this.vbox15]));
            w16.Position = 3;
            w16.Expand = false;
            w16.Fill = false;
            this.Add(this.vbox12);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.label6.MnemonicWidget = this.f_SshUsernameEntry;
            this.label7.MnemonicWidget = this.f_PasswordEntry;
            this.label8.MnemonicWidget = this.f_VerifyPasswordEntry;
            this.Hide();
        }
    }
}
