// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Smuxi.Frontend.Gnome {
    
    
    public partial class FilterListWidget {
        
        private Gtk.HBox hbox1;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.TreeView f_TreeView;
        
        private Gtk.VButtonBox vbuttonbox1;
        
        private Gtk.Button f_AddButton;
        
        private Gtk.Button f_RemoveButton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Smuxi.Frontend.Gnome.FilterListWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "Smuxi.Frontend.Gnome.FilterListWidget";
            // Container child Smuxi.Frontend.Gnome.FilterListWidget.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 5;
            // Container child hbox1.Gtk.Box+BoxChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.f_TreeView = new Gtk.TreeView();
            this.f_TreeView.CanFocus = true;
            this.f_TreeView.Name = "f_TreeView";
            this.scrolledwindow1.Add(this.f_TreeView);
            this.hbox1.Add(this.scrolledwindow1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.scrolledwindow1]));
            w2.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbuttonbox1 = new Gtk.VButtonBox();
            this.vbuttonbox1.Name = "vbuttonbox1";
            this.vbuttonbox1.BorderWidth = ((uint)(5));
            this.vbuttonbox1.LayoutStyle = ((Gtk.ButtonBoxStyle)(3));
            // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.f_AddButton = new Gtk.Button();
            this.f_AddButton.CanFocus = true;
            this.f_AddButton.Name = "f_AddButton";
            this.f_AddButton.UseStock = true;
            this.f_AddButton.UseUnderline = true;
            this.f_AddButton.Label = "gtk-add";
            this.vbuttonbox1.Add(this.f_AddButton);
            Gtk.ButtonBox.ButtonBoxChild w3 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.f_AddButton]));
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.f_RemoveButton = new Gtk.Button();
            this.f_RemoveButton.CanFocus = true;
            this.f_RemoveButton.Name = "f_RemoveButton";
            this.f_RemoveButton.UseStock = true;
            this.f_RemoveButton.UseUnderline = true;
            this.f_RemoveButton.Label = "gtk-remove";
            this.vbuttonbox1.Add(this.f_RemoveButton);
            Gtk.ButtonBox.ButtonBoxChild w4 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.f_RemoveButton]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            this.hbox1.Add(this.vbuttonbox1);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbuttonbox1]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            this.Add(this.hbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.f_AddButton.Clicked += new System.EventHandler(this.OnAddButtonClicked);
            this.f_RemoveButton.Clicked += new System.EventHandler(this.OnRemoveButtonClicked);
        }
    }
}
