
// This file has been generated by the GUI designer. Do not modify.
namespace Smuxi.Frontend.Gnome
{
	public partial class ChatTypeWidget
	{
		private global::Gtk.ComboBox f_ComboBox;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Smuxi.Frontend.Gnome.ChatTypeWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Smuxi.Frontend.Gnome.ChatTypeWidget";
			// Container child Smuxi.Frontend.Gnome.ChatTypeWidget.Gtk.Container+ContainerChild
			this.f_ComboBox = global::Gtk.ComboBox.NewText ();
			this.f_ComboBox.Name = "f_ComboBox";
			this.Add (this.f_ComboBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
