.Dd $Mdocdate: February 23 2014 $
.Dt smuxi-frontend-stfl 1
.Os
.Sh NAME
.Nm smuxi-frontend-stfl
.Nd terminal frontend for Smuxi chat client
.Sh SYNOPSIS
.Nm smuxi-frontend-stfl
.Op Fl dlh
.Op Fl e Ar engine
.Sh DESCRIPTION
.Nm
is a terminal frontend for the Smuxi chat client, powered by the STFL library. It can operate standalone or attached to a remote Smuxi engine.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d , Fl \-debug
Turn on debugging. Debug logs are sent to
.Pa $XDG_DATA_HOME/smuxi/smuxi-frontend-stfl.log
, and older logs are moved to the date of usage.
.It Fl h , Fl \-help
Show the arguments Smuxi takes.
.It Fl l , Fl \-list
List the available engines Smuxi can connect to.
.It Fl e Ar engine , Fl \-engine Ns = Ns Ar engine
Connect to a remote engine.
.Sh KEY BINDINGS
The keyboards are similar to that of irssi and similar clients. Note that some terminal control characters (like C-c, C-z, etc) are not intercepted. Common line editing keys that work in graphical applications will also work. In the following examples, C-x means Control-x.
.Pp
.Bl -tag -width xxxxxxxxxxxxxxx -offset indent -compact 
.It Tab
complete nickname
.It PageUp
move up the scrollback
.It PageDown
move down the scrollback
.It C-p , C-PageUp
previous window
.It C-n , C-PageDown
next window
.It C-Left
jump to the previous word
.It C-Right
jump to the next word
.It C-w
delete word
.It C-c
exit frontend
.Sh SMUXI COMMANDS
Like most IRC clients, Smuxi uses commands prefixed with "/", and most use the same commands, also including its own set of commands for the client and engine. In the following examples, the "/" prefix is not included.
.Bl -tag -width xx -offset -ident
.It exit
Exit the Smuxi frontend gracefully.
.It window close
Closes the current window.
.It window Ar number
Goes to the window with that number.
.It connect Ar protocol Ar protocol-parameters
Connects to the server with the given protocol.
.It connect Ar network
Connects to the preset network.
.It disconnect Ar server
Disconnects from server. If no parameter is passed, then the server associated with the current window will be disconnected.
.It config list
Lists the configuration options.
.It config get Ar key
Get the configuration key's value.
.It config set Ar key Ns = Ns Ar value
Set the configuration key's value.
.It shutdown
Shuts down the current engine.
.Sh FILES
.Bl -tag -width -compact
.It Pa $XDG_DATA_HOME/smuxi/share/smuxi-frontend-stfl.log
smuxi debug log
.It Pa $XDG_CONFIG_HOME/smuxi/smuxi-engine.ini
smuxi local engine config
.It Pa $XDG_CONFIG_HOME/smuxi/smuxi-frontend.ini
smuxi frontend configuration and remote engine list
.Sh SEE ALSO
.Xr smuxi-frontend-gnome 1 ,
.Xr smuxi-server 1 ,
.Xr smuxi-message-buffer 1
.Pp
Website: http://smuxi.im
.Sh AUTHOR/CREDITS
Smuxi, including this frontend, was written by Mirco Bauer. Contributions to this frontend were also made by Ondřej Hošek and Andrius Bentkus.
.Pp
This manpage was written by Calvin Buckley.
